package com.czertainly.core.service;

import com.czertainly.api.exception.*;
import com.czertainly.api.model.client.attribute.RequestAttributeV3;
import com.czertainly.api.model.client.attribute.custom.CustomAttributeCreateRequestDto;
import com.czertainly.api.model.client.certificate.*;
import com.czertainly.api.model.common.NameAndUuidDto;
import com.czertainly.api.model.common.attribute.common.MetadataAttribute;
import com.czertainly.api.model.common.attribute.common.AttributeType;
import com.czertainly.api.model.common.attribute.v2.MetadataAttributeV2;
import com.czertainly.api.model.common.attribute.common.content.AttributeContentType;
import com.czertainly.api.model.common.attribute.v2.content.StringAttributeContentV2;
import com.czertainly.api.model.common.attribute.common.properties.MetadataAttributeProperties;
import com.czertainly.api.model.common.attribute.v3.content.StringAttributeContentV3;
import com.czertainly.api.model.common.enums.cryptography.KeyType;
import com.czertainly.api.model.core.auth.Resource;
import com.czertainly.api.model.core.certificate.*;
import com.czertainly.api.model.core.certificate.group.GroupDto;
import com.czertainly.api.model.core.compliance.ComplianceStatus;
import com.czertainly.api.model.core.connector.ConnectorStatus;
import com.czertainly.api.model.core.connector.FunctionGroupCode;
import com.czertainly.api.model.core.cryptography.key.KeyState;
import com.czertainly.api.model.core.enums.CertificateProtocol;
import com.czertainly.api.model.core.enums.CertificateRequestFormat;
import com.czertainly.core.attribute.engine.AttributeEngine;
import com.czertainly.core.attribute.engine.records.ObjectAttributeContentInfo;
import com.czertainly.core.dao.entity.*;
import com.czertainly.core.dao.entity.Certificate;
import com.czertainly.core.dao.entity.acme.AcmeProfile;
import com.czertainly.core.dao.repository.*;
import com.czertainly.core.model.auth.CertificateProtocolInfo;
import com.czertainly.core.security.authz.SecuredUUID;
import com.czertainly.core.security.authz.SecurityFilter;
import com.czertainly.core.security.authz.opa.dto.OpaObjectAccessResult;
import com.czertainly.core.util.BaseSpringBootTest;
import com.czertainly.core.util.CertificateTestUtil;
import com.czertainly.core.util.CertificateUtil;
import com.czertainly.core.util.MetaDefinitions;
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.client.WireMock;
import org.bouncycastle.operator.OperatorCreationException;
import org.jetbrains.annotations.NotNull;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.io.IOException;
import java.io.InputStream;
import java.security.*;
import java.security.cert.CertificateEncodingException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;

class CertificateServiceTest extends BaseSpringBootTest {

    public static final String CA_BASE64_CONTENT = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSVlEVENDRnZXZ0F3SUJBZ0lVSWhGc3h0YjVESHFOZzNMNkpKZHlVV0lKTGdJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF3d1ZTSGxpY21sa1pVTmxjblJwWm1sallYUmxJRU5CTUI0WERUSTFNRFV4TmpFdwpNRFEwTkZvWERUTTFNRFV4TkRFd01EUTBNMW93SURFZU1Cd0dBMVVFQXd3VlNIbGljbWxrWlVObGNuUnBabWxqCllYUmxJRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwWENhakNkWDZ6SUsKL3lHY0IxYkVhb2RBZjFPWVZmSFFVVy9iUlpGdy9VeTFjdUhicFlZTnFXNEcvU1QvUlJJdERVajkyUFM0YjBPSApaSFRqR0FCWGExL1oyaFpOSVpFcE5MMzFkNDNLKzJMemJNLzhCZkdQT1RFbmMzTWdoWnFtVnlqUWdKV2FFV3FMClVOMjZIRzFsL0QzN0R1MElFRm9nV1lsaVBrWU5HcTVOcU9Hd2trWGVUTkZiK3JPay9SUDJDS2NYclZOV2Vpcm4KV2lXMXZ2WEJlZ2pqK2pFRmZNUHJtN2Y3RXB2ZU5jNm1FVUZlNkxkcHRXaUFNVklxdlo2MUNSZWhEZ0lMWHRnWApQNEZpOFErMlR5djNzd1lMenRCcm1EMENJbE9lbFluUkhVVkMxakVTL05pSVRLR1N6c3lZZmhvbmk2TlJIbnlKCjdOeUsxRWFyQXdJREFRQUJvNElWUFRDQ0ZUa3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWZCZ05WSFNNRUdEQVcKZ0JTV28xV2k0Snh6S0VXYks4N1lYNEE4T0ZvY3RqQWRCZ05WSFE0RUZnUVVscU5Wb3VDY2N5aEZteXZPMkYrQQpQRGhhSExZd0RnWURWUjBQQVFIL0JBUURBZ0dHTUlJSHZ3WURWUjFJQklJSHRqQ0NCN0l3Q3dZSllJWklBV1VECkJBTVNBNElIb1FBc2ZNUExWTTFHRnB1ZElma2hPdnRseloxdUxrZ1JUSGJLd1dYU2dMKzFVOTM4bnI1MlVVNWMKaG1qK1RKMGZrdEZFZzJPbndMeDJ2ekY2ZnRQT0c3alYva21ydDJlTVhwS1FMa01PL2ZrbW5xQ1dxTkVpYU9YZwovY3pPNXlUNkRIWlg5RVNpZlJZTGdacXdUY0M0SVd5WC8zWWlseUlwUW03T2hTd2hONlU0aHJBR1hxb0VVTWN3CjlZL0lNdWRTK0lNcFo3T29YdjA1aWloTUdDZ0c4QWEzYWtIcnRUQ3BXVU1MUzM4TFZJenU1UVhOd0Rmdjg2bW8KMnBjRjltQzdTSnNTRE9Ja1VYTjlIbDc2amkrQUduU3BTa3BLSlB2aGllSUJ2czMwbERBd3BmMXlXd3MrUWZrcApCOFVEN2MzRjZDcXNvRTFPbjA3MUpkb1A3Q2tBWlpmUEVKZ1ZMVjNHRStod1lnMHFESVM4enRtNGVxTzc3RnUwCjdOeWJQOFJPWDIrQVpQNWJhSklydTdYR0oxTVJrWG9jOVJIWmxPdWNjdW9aWXFrU0VLM3JtNk1JcGdYbSt3M3YKanJ1c1hybnZWSnZTdGNZRTErNlcrNWt1VzBCMnVBTXJabkZ5cWtJUkRQMU5kaktPWStvZG4wQlA3R2hkRkxOOAowRndvditkV0t2QTRRUmhjbWdUUEIvUW9tNnZlVzdNcHdJZ25OWlZxVHovakRKRmluSnlOSU92bFZaWUtEQ0dDCjlOWmZocWNrUkhlTFN5ZnUxc3E5aXMyWmRSbTc2eEZmcFJnU2hHdmFHcGVYMzcvc09MbzdzeU1OdHAyMERiQUcKdk85LzhYRnRwc25TL0doVC9UOVBsb0FEOXZoK2FxSjBJdkltVTZGOXY1a0VhcnY4em5MeENLOUliMm95SGpNSQpRYzhPWGVVaWt3WEpLejZZTklXMUdFOFJwUFhRNUF2NlJDWUxabnpLNlpPZlBjZXZKdFZhZ3lSNmZpMUVWT010Ckp4RHpaMHVXVjJRZG9kUDdUZ3Z2OVdIYlBER1Q1eHFsTkZHWFA0QmFwNDl3OXpQLy9LZit4VG1ZRmJyUWVCaUUKTjcxMkd0MUE4OWFkM0FYTUhFSmNhaDBtWmI4ZFlTZHJKNUhLVDFQMDhKL2Ryd3FuREd6V2tOQlQxei8yK2NybAozb3Q1WGRjSWRoa2dsUzZJbzRROHZqckRkU24yY1M0VExRWjFmYzZQc2t0YlJLVU1PMG1QWXJxVzhUajFSREVSCmFSY1lEcFZxTDg1V0s3RzdJZUJ1Rll4REtRSktJOUM3VTFES3A1TmJrN2s1WTdLMENPeDB2YUlFOUN5OW5RWFoKdVBZQjZYM3BZUzlzdml1VmtSdGNvc0pheHdGM0E3d3owZTI1T2tyTmVocW5ad0FDTnZRZEd4aGxUYS8xdDFxQQpkK2ZXOGtMaEtSQnNpVW9aREpSdDB2N3ZPRk84aFlUT2VqU2lZWU1jNnNYcUhpdjVOUThQZldMOFhCcW5JNXh2CkhacCtvT2dEU2hIRlFvWi9kM3ZKOUlZN3MwaEtENTBjOWorZ0F6VWY2cFFyaGlqbkRITVNSaGtWRzB4cHNEbGcKUFg3Nm8vK0NOMnZtUFRFbHdwTFV5UmFtVHd0bDU0eW1YcVlsTXU1dDU3T2wyeUZVZzNXcE1XMmNSM2dvU0hFegpSTDRvZzFhY2U5NzBUdnprZHZ3ajJCRGhVL0tZaU0rMnNrT1pHaENvM29mSk9kNlRtVjJXbnJNMXpaaWhOVi9CClY3QlQ2Tm83emdIZVkxQnFabG1WNWw4NEowRk9PR0ZKY3RjMlVBK3YrNkxsakJDMjI2WVVKblg4ck1vb3UxbkIKSWxBQzcySG84R2JhSzNGUUNWMHVGanZjQ0Q1UDNqRkNxTThxMTFXWUdOWTNwR0gwZzhVQlNaamhoM1VHZWxtMQpFUEU3TlNPTmdSMGhnRGZPT25jUzBkVUdyQkZTWGJqcndlNGFreHoxRzAvb1ZBeXVnUnNESm1la3RtNkREUEpPCnltQUpyd2NNdzl0QWF5OXgrdDBXY05ZWVVuZGFNbkVkQjl1RGN1S0dyZk9vRVJDeDFDdm92Y1l1bit1OVpxaXAKYk9YUUZlaEIvSjJOajA1MVRVaktwZ1ZsR2k5MHhDSjNEY0JsNTZiNWh0THk5dUFKVnVoL2tFSzZWOGRvbm5BeAorK2NGYlYyL0M4MUwxcDFVQUc1UUJKeGJEOUdndjBrSVRIWFRLRVFQMEVjSmNEVzhhbXprMnc0RGZTZCtyY0gvCkVLaXpqN0R2WmVvRENiSEVaa2NGQk16ZVV2cG9oMXZLN1paMFVBZjgxVGRHMS91ejBHMGk1c1c5ZjRSRDU3SjcKRzd0RDZXMnZEQ2Nic1lmZ1pEOFZoOFhJMXFhRzZOSVdDVHhsMHZPWmdzUDY1b3B6WUZhNWx1MXNvZFBXVHBYcApKcy9EWkRJbG1QUHlqNUdjREZNRWZ0KzZ6LzRUSzBnQzhyZ3RZbzF4OVErU0ZvN1l1eGwxcUNlS2Q0RWd5UnlmCndnOERxZDhGWStlWDM1QmtLbEZURGdHOWVuZFJqd0t6SjFjMlUvZHMzS1Z1TDRLNHBtbTR4ajUyaUhEcGZhZzYKaWZUeFNTaW9ycFVyZEdVNGhjTFpTMVJNT1pab3NXYnVuSGo1NzdpNTViYzV2d0piMDRyMWh1eWtBZmpsVTg0Mwo1cTFaQzA4K0tBaGdnZkVyOFM4UmxBWXhHQWpXWm14TEFnSGhxazB5OFdNQlpXak9nd3BsVmIydkJFUFR5QmluClRrM202c1R4bGZaQm54U0xTWTFYcnJsZE9Hak9sRnFnNnQ4ZmFxWmFtWGRsUFcwZFpIL2tsRlB1VjRnUWE2UTMKN3hHWTJ3M3JSL3ZPS1psd05yU1FWMmZtMnVsSERHcnpQemo5TXQxSWRrZUZ3NXJCRFBuZndwZjhzYmd5b2tnSQpOdkRaVzdpM0ovTllpNVZqWit4RERMeVVtZ3UxcEVoUklMTEZnVGlIbkhzZEJTNkdhVEhLRlR6WkM5QnE1aFlHCjhCUlVuajYyTW9NQmV4ZEV6bWJKWlpPMUs3cUlwS1NORVhxZm44QlJBZmJXMDl2OGRHK3M2YlRoWHY2WVYrY04KZ0VQQ0hmWEdDNEdpSmlQakxBRjE1M3VhYlZrZEJmKzVLZG93R0RqRlJMRVFlSlRnZW5FOFVwLzI1NXdkK0xrVwo1VG9NMDY3eXFybXAxTlFMMkt0dFNUOFZNRHBlNUUyTEZ0Mi9JTEUyNmVKQ1NPNUFuZm8yY05BU3BDY1puZGllCmFJSXl6ZUVhUmpsNHRvV1doeVBGeUxYMTdkZk84cnZiUzFWQk5SZHI5azlnNXAvZ2h4RUw5TWlYKytkZlArc1MKTHAwbDBQQ2ZSSSs5Qm1CVEFVbUU1U1BHYXlpUGRTeU5oTUo1dzRid3h5a2NXRCt3S08zK1JEQVVCZ05WSFVrRQpEVEFMQmdsZ2hrZ0JaUU1FQXhJd2dnejdCZ05WSFVvRWdnenlBNElNN2dCMHBkVVlseDdXQUJETGgyQWlEZGRFCjdGTU94cDZoVkxDNk9BTUxvREpaQTl1SjJaa3ZjbVppejV3b2RpaXRnRmJsKzUyUmZHd2JWUm9FeU9QOU5iRUEKQ08xRTRiVlZJYjBiSjc2dm9hMEVvVjNjTVFZcWpmNks5bkhBTTExZ3VNOVpRS2JucEJDckIxbEVaaWlTa3lrRQpYQkZaZDArQUVCb0N3Qno3TlY2akpVTDJvcmJrV3F6WWRHQlg5MnpDS2dCWnZVbms1NnBFMWhBU1lhZXYvenNXCnBTNHdLQi81U3c4S2lGaGhjemlBWHU4MmEvM0xnZDNiNXd3dGRnUjJtb2FERU1VUmpqU2Y5b1JLdER4ZUZKcDYKS2VnaURydzdmTTZrMEdtZExyemdlUzdRdUNkdXlIODFQNWY4MXpRM0cvakJDeXE0d1QzRjNESXl4ajVPTDFxbgozaytPY3Z1VWxwNk5oZzZIV0pOY3VCNW1mM2JEcFFVYlRmR0kxeHJhTVVIRGRqVHRmYVFvbktBeWRMN1pVK3NXCktGc043U0tZS0dBNEVnVFU3SGs5WkhzTTFoTzRlVVRQUG1EYVhkekVORkhqWlpkeCtJK2gzODVHVWplN3VPUjAKckw4VjJWeE9aMnd6b2U2ZXZQRWtsUTcreUE0bWNXRmtXcExMU0ZIejRxSnljUUxkcTNDUFUrMUNxbjUyRFNiawpVTFNjcFBNd1VaNFkvUGhtelFUZ2JwMWNPVHp0RzV5STVTNVNGbDMrc1FLZDBCaE1Eb0QyelVSWWpVT0plR3BDCmRaanROQloreDZYSG1mYWdydjVLSThTY2lyZ3VOb1ZZYTIxbnN1d3YvdUI5VStXMkJQeEIvbGQvYlhXS3EraXkKZ25VL1B6cjlPbERvQjhZNkMvckFyVUJmdTVlS285b1pKZm1iSFRDOW50dFgyZWFRVWhHVU9WT253cXJnVXVKbgowMGNnWGZ5b3U4TENKaHRzcEdVRW5tQUlQVTlscEdLSElRVzRJWVc2eTNmVUtkWk5OUVZRVitsV1NBejNOM2pMCkdLczVCVVEreVQybzdrQmhLZ2l2UVczaEdqY1RIZzlsVUdUQXlXMkpIbnQxY0VZamlLbjVJK0MvN3pRRkkwaFoKMGdaKytBb2xXK2J6SVdGQU9kcnVraForME1qNXdsMnVnTUVIZ3BKcTk2eFA4dnc5Vkt2b3JPMDNqbnZiV3BQZwpwV3phMmFMSndWOUlhYjErYzdGbU05SjZOclBzMzQyaVVLVXhlL3pMcWMrcjY4UVRHKzd6Z3F2U1dib0swOERBCk5sZU1vMUl5NGZTWTB1Rmk3NEVlbVhxZHZhcmhuQ1BZRmJpRk1kcHFPOTFUMkJobEd0cG1PTDdiVHQ0NXJubUkKbU9sbytGbmlWY1NHZHdWMlY3bVdVN2dPTS94VmR1enZsZVc1VjQrbko5UXhUQmNWQXROMXhLdXVINWRNL0IyTQpVRUlmd2E4NG9JWFJYS2pFTkU4aWExWGJPOU1tQXZoSDlNN2lWMm9SdVF1ckM3N0xhb3RLNWtQTXhnZUM1dkdhCkdyTkRWeVRLaFN2TVdZMXRwLzdWZzM3OXZHbWJnOVNVUUFXK2Z0b05PSmNMQVg3bWg5TnpnZTBMQXpyeCsyNXgKaXBCT2dPUDd5NTBEekE3eEVjOFR4TENsYmhSMjZNY1BaVUpaZis3NlpSMlhQbU5CQVJYY3VwZmNLOUIvMENxQQp2OVVsdEZEV3lpazRmdnRNZXp6ZGtwQWhhK2QyUVVoRi9mVUs4WDFRRjFnbnliUDhEb3U5cmEwN0hLaU5BN2NGCkM1dlJrV0NNRVAxYW9FbFR4b1VPcm0zTmdqTjM4UmFFcHhiaHlCLzZMNlUrNDhMNlpRckN0c21MeTZublFVSVcKaWRTdEFRQXNuNTNqQU5oSll1TllHdndnbXdKbnBtRFFyVjhiUGNOcTBpZFFtQVdRMXVsU1RBVklFM2tuQnVzZQpZTXpOVFNtMG5QR2xrY2F5cDBJK1l3amZSR0dOQk9MMmE5cDFSeFdrc1l6Y2VpOGdjZFZXQkxKQVlHVFdCM2JVCkVLR3pBcjdRVGJxNy9YUFVJMUVBaUVaV2UzSFgzMFlBMWJrRUZKNDJGVnJNMHkvQmNZbi8rSzZRSmJaVFdZVWsKbHY3dTF0bDI2WnliRG5ibDdiZjlJbmVtUkZZQ1BBbTUwdDJiOEVpQVQwSCsvTkxmZXNDdmpBdEVRREhUL1pndgp6QUM2V3orZmE2WnIwOXFrMUtkSlVmNUpXa3hMKzdndERWd09DUVpmNjNjVnJjeG5NYVl1Q3o0d3ZzNGRsbk5JClhMZTgvODQyMHdsY3dtejdUVmdOblUrN2IxdGxnNHNTanlNMGhxelVNWldaZ29rZmwxUm1xQStVbFNDN1pDeXUKd0EwVVdNOFVHWlREdjNoK1ovY01VSklaVENuQ3dvekxTb3hLUmgrZ1dnWWZGcVBCTXMraDNoNDB2WEEreUhJegpMNlVyWTBqbnZhYU5lVjBmM0x3NWNJc2lWSzh2TmNIUTYwWkVBeTVCK0dZNTN0d2Iyb2tJMG0ycVAyOExUZEg2CjdRNlpLNlpSKzVQQ0d3THg3L2NYMXpEMUtxQnFrTGx0NitmVFZFa053OW9lcWZXQWZLVUdENVlHSXNnVUZXRXoKTmt3Y0R2YkUwS3lFY09vbjdPS3U1SXhkSm5YUmxyVmlraUFxN3Jac3pQN24ybGJLZmh4VEF5eVJYQXl4aG5zRgpUWE1QeFZzeWJsUjRQaFBXeDQwVHdYdlZ1VWxCa1dDV0cySVovTHdEbTQrQkRXMjdwTlB5eW12K1YzYmVsWEJ4CjFOVjhMQnY3Q0lzdmh1aFFOYWVpTm1mcWR0eGsxeWdKbEhON25XUCtiT3E5TUxSYW1mM3g3VFNmYzdBVWNkODUKNE9ORHpDeXVxTHF4bXpZaGd4TTF3dVh5V1RlUktQU3FwVFV6OWZ5ZUhZWlBLazRaQlBwL0ZJYUhkZGdSQUgrawpmem5lMGgzOXdVb2YxQyt3L3RVTGg1RFo1UlVyWkM1WloweS9sSXVVclZFeFdZWkx1M0RQQkV6TmhQR0huQU1jCnJZS1VTZ3BsU2J3TWJOMFU3M0hnQTNqNDc3RHJOWm5aNHpSRU96Qy8wT0NyTE5RTGpQdkVkRDFodUo5VURZV1YKWXNaSWt2c0l2MEtHUGZscDlKeSs5SUFhc2ZyODIvNUFUdEZmMHRGc1ROYWI3SU0xTmxZb1NRRCtvMEw5d0REUQpZcmo3cEFVZGRLVlgvOFFBSmQ2T1dTOEF2WmI3bkpGcVl5dUFnaEw1THExcGpoTkNqL244TVFSWjhDTDE3UlBOClQzOUp4NlZhN3VYSmRaN1hIYjBQTFBnQUxoeGZUOXZRY3VHTFMrcmJiblBWcGpxVGQ3ZERKZk1NVzgxUDJwaVYKcDRaRXAxMURER1dyM1licWRzU1c2UG5YU1I4ZDF0Nm5Qc2trdXlBZFFVN3J3RjhwRUxxalF6R2Rpb3E0aVJ0TgpsK2E4MmhuZVRWald1a3d3ZnZGa3FpWjRiaXRKdkNZMlFUN2pDZ0VlcUhCS2RFWi90OEYwc0NsRlVlSTdDbVRHCkFjcVVvMHdmTDViZ0lTbmhydjJZR1JrR3BWVGt6QUNBU2kzNHhkckVicDl6VW5RYWJRQXFLdXlTcGN4RzhhT0QKU2tZVHh2bHhZWldoWlJDRUFyNGxmd0U4cys5RC9NKzlBNGNCd29BTE5wM0g3Z1gzeDRKSmtEMTdZZVNQSkg0cAo4QTQrQzRIOXBwNy9qVFhpc3AwTGJtODgvSWl6Nk9BN1E2blBUSUdtTFk5WFQrcUlFRHJua1ZwWWV4ejNEZ0RoCis2eDYzelQzOGJZT0duSEpNa3gzY1lpTS9YQWRRaTZGR2VhK3R1MFZJVktoenplNVNUMDBZZStTOGFzbGt1UEUKakthZXN0Y0N2RjBvQWQrY01nRm1YZUl6TTRvK0pJL3lQTDdEM0RwcnUxUkVqK1BjK2NXQTEvQmFvQ2Q2cHFnaApQNWwzUFh2MjYyZXhvanZGa0pTRWQ4L3dEVnNLYmhGb1pYOENSZjJZTFVEUWc2bDZ5WnBiSFJ6ZGFObXl0ZmFSCjYwMCtuaXYyNDc3NWwwQ1ZoUmVIWlBBS2pFNlFQcTR4S3FTQm43SHNNNjdOUGRFMDhxSVNIbUdWOWNKNURiTEkKZHFoVjRMOEdrQXV3Ymo2U1hzaUFBeFh5cjloclA0eTFqbUtaQmVZRHBzenZoUUFqbWpnVUwrTC9tSXU3bS9ZVwpjUTQwYmN2TjFLb0pWMkhOQVR0NjluZ1FjYmIxZzBkanhpVVNNTHJOVUJXb1ljckgxMW5lQko4aFY3VHM4T3JhCk9MSUF5WnBYZ0lEUWEwdFNpSEtvK3FCaTVNZmUwcEQ2NVJuQWNPRFFrSHRXSHR3RUpaM3V2L2paUm5SV3lrVWcKOTBJYis3bUlSNkliajBPZHJZRXBjNmVIeXR4UVQ1MFM1VFZoSlNaVWwxQlRiU1IzTVlmRjdaSkN6T1hXWGxaVApOOEJBZk9EQzREdFk0NnFvTUFtYnNQTXljV0V6VUxVQ2thcGtoRGpKNDBUOXo4ZnQ4WDJLQXV6REkzek03cXVICkdNSWRud1JCdWRCRy9vUjZXVHlUcWVFZ1Nvb1hKa2ZiL1V6NHJnWlphYlhlbjNiMXpURWp5Y0t2dWNjR3FVbksKY1NhTnMvNkhMK3BjZXJ4cHh4em80QlIvWGpiSHFiNlU4bDgzaFljdWw4cFRCbFlyb2hwRjNncm9qb01pWW5DUAo0ZU15dGpnTXBFS0NtSWxrbis5ZjU1RVZpTUljMml5QzVCaFF2VGkxWW9SL3VFSlhncDFTV2NaeEU3eGJvYk0xCmVmU0FYSlk3aWhqK2cwaEdHWjdsVy9UMVlIdXJHZWZ0VWNORFNobjZ0Z2JVTzQreW1yc1JtdnpGUUtLYWZsd0YKcTRaVHQrWlJ4dFhSUG5YdzJkOGhib2ZYWFVBTDMvcWNPc0ZyWjRtT1BYZDlSdDV2RmVYNjRYMCsrb2hBR210dgo0bTB3QjhOL0tjclUrekszK1k5RW9yZHRlN0NrZTkzTG4xeXpZZTNLOU5leDZ2M1luVTdsbXNxMlg5cndWVGowCm5HK3dzREhWU1NFQmhBWmtVcDZzVnBUbGtsS0V6RVdwSVJTK0UrU2FsMkQzcUhzSEZyWkVMRmhnalBwWEUvdTgKQTM3a25OMURxYjRVNkoxeFA1cEx1dWlGbWdSRVNxN1JPYXE2cGFZYUwvNndCTnQ3UDNlcjRqaGJyOHdmclhZdwpmQjBqWTd2QkFhZTl1MnVFZVZsb2NUN3lkRjJmV0g2RzFsTlJaUGtUUTF1R0hERHFJeVFTNTBhdHJkb3JBb1hsCjdWL0Vna0Z1RCtvbTFHVjVkNDZqVEVRc3dxaGpJSWNYUDl6SmdQV1NOK2t0RnI4d2VLSXBMRUk3T1U5WXF4MXMKbU4xUDJhcHg1VmJxZFNyT1JUbTlFUGMzaEV2dEp2cFovVy9hT29sYVAyaUk0SlFkWFoyUklaYUtDU3prVzkrbgpOaDRraERoUXRDT1djcnZ6QWovQ0xzRDFDQk9GL1grYTZwMGNNek8yODJJY0duTDVMNXFzRnB6TkdxVnJ2Y3UrCmN2RE16cVV0ejliVUtkSzVuOWZwb3lsSFliWXNtL2ZnYUJOeFRLY3hwVUlNQzAvcHljYXhhdWg0ODAxZlRpZ20KMExLdlViSkUzSEp5MTZ3Rk40Zyt0bE4wZTRTRnFmNEhDeEVVUzRQRDQvb01WYVd6RHhOVWROYmhJVFpBUTRXTwpwNm5GSWorVG5xS2x3TWZPQUFBQUFBQUFBQUFBQUFBSEVCUWFJeXd3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCkFCWEtTbWIxalB0bHpEVEg4dFRUemRxVHRIQVBHeTRieFdINEJ0UkNPNGVoOUhMTFNnQXFmZmU5RnpWZDl5aHMKdzhnc0dHQUxUTlh5WEswc3FuelgzN0ZhSzNTS2ZhZ0gxL1NyUFIxZGVzaEo0M3VZTjRRSEl4QXFQNGczNDFTRgo0bThsWGdXcTZ3S3dBbzMwK08vMnRxWHlGUWwrU3BVcExUbnNBZ3NIdVhma1dDdk93MUtiN0tOdjQwVXhRUVE0CmVsbVdyNHJrbHUxTGdZbWdsd1FxWXhoQ2dGdldLZkw2YWdkcHdZOG5OQUVNK1VsSmZpbmxQc0UzUzRtNUN2elMKNE01K1dIaGtHQkNuTGdocmRUa0Znc0lmdEVyK0ttUFdYdGVQRWhWLzBmcjNFYmJsT0FDc3B5VjM0NC9iSUE0UQpmaXhCRVhzN290WmRXZGtJVTAvRlo0cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==";
    public static final String EE_BASE64_CONTENT = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSVpMVENDR0JXZ0F3SUJBZ0lVQ0FrR3NGSG1oeERxSnJzek15UldqMVBFNVJjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF3d1ZTSGxpY21sa1pVTmxjblJwWm1sallYUmxJRU5CTUI0WERUSTFNVEF3TXpFMApNVEkxT1ZvWERUSTJNVEF3TXpFME1USTFPRm93R3pFWk1CY0dBMVVFQXd3UWFIbGljbWxrTFhkcGRHZ3RZM055Ck1qQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUtxeW9WR2pjRGZycThKNStoTTMKK3A5T3BjVGVrcWxYTHI0WXprbitxenpwTW55NXl5Q1M0UFZPaUhRaytBWWNyN1NhOUFxZ3BVOVNkUXlFZk5DbAo0enRRY25JV3IzMncwMjJIUHd3WGpLdjhMbmNoMi93UnROb2pSWGg0QUhzdlZmY2RFOGJyUEJvQjkzODFLanhrClVmellsUkVGZmp6K3FxL0s3Y2RZekVia1JRRWJoUldlamtrZWlsaWJlR0NvTnNDZHRVckE1cmV1dG53WW13R3EKcTIrMFcrcHgzTDJMNEFsK0FWWVhXZ21mMmxIaXNKL1J0ai9FRTNiRTRnbWFFODJKVUgyaUVIQ0F6eFp3TzgvVwpvYzdXMHBLOFBQdEtXUTVkR1p0SkZ6WDZoSTZCM3JGUnRBalliczluU0hBbWlPcGZsUU0yVmM0eEtiR1VkWGJaCm9FTWNwdHNwTzhtYkdsendmS3lrMEVjQ3M3bEpWaW9zSm5KMjFuQ3VrOUR5WkdKVHBVSE12OThWY2ZhMWwvZU4KNjZtamhOSW5kamlxWW1tdGhQOUJuM3NhSDYwZHRPUDVQTVd3WXRjRmYwdEVOelVTeW9tbzBYQUF3V2FTMzFSbAo1T09uWXJkYWtVdVpFU01IaEN0d05XVDFDbGI5aGUwS2hBUko1WTlYd3F2SWJTb1RJT3YwVG85RmF4c0liWVd1CnVpYVlHNHhXYXVTNDZXT2tZeVYvV2RYYWJFMXMxbENxOE9pc1JqcHRRZUpNVkwxNmMweFVQbFZ2WHcvYXpXaWQKZlNkajc0UWJMREFvOElObnVLZlM4OEd3NWVZbXNBanVLNFdtbGUwYnVjVFNWdVBES1VWNEhrRGpKdkJHOGJiVQp3RU5LMHFGU1plREVMcy83cTRHOGZ2eHpBZ01CQUFHamdoVmlNSUlWWGpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHCkExVWRJd1FZTUJhQUZKYWpWYUxnbkhNb1Jac3J6dGhmZ0R3NFdoeTJNQkVHQTFVZElBUUtNQWd3QmdZRVZSMGcKQURBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQWRCZ05WSFE0RUZnUVVsajlnS1pIRGwxL2ZpaFdrdVprYQpGTktBRW04d0RnWURWUjBQQVFIL0JBUURBZ1dnTUlJSHZ3WURWUjFJQklJSHRqQ0NCN0l3Q3dZSllJWklBV1VECkJBTVNBNElIb1FEelAwQ0x5U1oyVDVxVkZHSTVxOFNHV3RUY1hiTE1sV3Q0VVJvRDA5VU1seVJDOHZUMEgvcTgKNmljZTM1RzdERjNiTS83WFVrRlBpUy9LazBvZWhNREFKV1dRN296SWc2MHFZOWNNcTRSSmxqQzh4cHpGQ0tiWgpFcVBrQnVBRlZ4bjd6aHhUbnVPMkFmTzkwREFMMUlGYVpvZDNGd1ZtL1kvSXJJbVNMaXlENk1yOTBEaXBaR3hKCkFCcFR1Znoxd0FFeGFZMXNCQzBoV2t4Z3NnLzJ6QWhxU1pDOXMvc0JYSWh1ZHhvcklaZTlKSm9wUThxRndKd2QKR0JPb3h4b21PRTNnSFg5NkJZQVNXZmVndWxCNFFNT3ZONXB5MFB5MmM0d3YvOTcvK3kxa3ZIeVQwcWJiYzhMSAoyci9vY3F4dXpEYlU3b3BYMFhzK2lUb3BkY2FlRENEaXpKM2UyVmR2dHNUZnFZYTM2VUFqU2g3UjdKMzlhWGphCjdUdlA5YnJiSGxTSUdkUU5zUFhwbUFvWXd5Zm1oMDFyQTdUdndaTEh5RVNneS9tYU1lbU9rSXA3TnFFeXYwcUkKQWY3NDRHd2hqVVNLQUI1dHpNbUpaeVVBRzFVOEc4OFVQOVRBSllIblJiZnB4ZjAzTU05WUd5QU1ucFlTT0VjNApuOW1DNDJ0MUlBdW03Z0NTSFVma2FaZjF3SFlGR0h5akRUcUsxNmIxZTF5dElEemhIZWIxN0F6RFcxci9KSWI1CjVKWnFySWJldU1MYXFFS0o3SHFCV0VnOTBrcEx4K2MreUg1ODY2aFJ4dVozOVkwWEZuNEdlSkFoRmlCdDhaWkYKd3pUaFB5VUw3UlkrT2JUOVA4MnZ5MkM5eFpScm5XbDI2VysxQ01hd1IvMWtUU1lnczFWUGRmVE9NVnJ2UGtGOApzRyt0RjI5eU94dWhjMk4vb2wwbFQyTWQ0NnUyK0JpYitGWXFlc0JLNTZqemd1ZVdFYjZ5YkovTmFjYldwOHlXCmlSdmNNTDFLeFVpREJyR2R5RjA2QWZwL1FPNHBzZ21mRWZSTjY3d2RtYUQ2eWVKYkVwblFMTTBubTZMQ3pPcUEKaUNBLzJ2TmxQSDk0ZVlvU3c2YW1qRlFmSWd3Y2pScGE3UHYxVS8vMU9NZlRWR2hld3ZaUU1TdGJ3N0diRGVUdwpaSElwR2txZzZ6LzV5L1VUcjlaQXc0RDUySjRYci9ERkdFUU9CN200TWtxcGVsUWpVWHlHN1VNV1puaURzSmZxCjRGQ082YVE0bkp4ejdTRVR2bHd6VHZZa3ZrVGFGbm5oYUFDNWhwZ0hRNEhISm4yUkRFSFZEaWE3TFBXQThaMGUKVG1uVDQ5a3hQb0N3azZEVzNuR2dRSFFidG11RGUxZ1JqZk1HQ2ZUeE5aMlFrVlMzTEVTL2xaTi9WRjBLSU5PVgp0RVJMU2puQU5GQ1FzelFWdXZzU01XOXIvNVJWL3VKUzlQN0t5R3E0Ym9NRCs0YXh1WmlXU1Rwc3M1TXJBWkp6CmVmdFFmdFFoU05nS2E4Ykh1ZTlMVlNOVUsyOW03SnFEV2FMWEFPMTZYdUc3L0J3ZFJkc294bHZyTzI1UG9XUnUKY2ZwZU1ab09xQjFXTmNHRTd6ZGhzT0dwTElpRDBTWkJHVUhGZStSUnJyTEJSVENsOU94RFVNbGoxa2NiVzlXcQozQ0M0Sm93QXFZdThteHFSMmgzY2RQK095QTBTbUo3WVFjV0RFdlZnTks3L1JYUVF6N09MQXFtZmltZmthSEl6CnVGdnk1UVNXZER4UmY3ZTkzdjhkMjZ4QllCeVVLcXRpMW11ajkvZUMzb1dMVkhHUTNFQXk1dEJxS05IdVhqWHMKZk91aU1wL012VFZwdG9TM2hFNjhnZUJvL3FocUJQUTBQdG5yU2hvZUJyMkpzOE9FWkM5Ri9KU2FMemhjZ0JMNgowZnhnc3ZkM2NPQzY4RGl3ZlM1bEN4UFFxczJreE1IUmVNazZVYzBRSG5ZTWEvaEh1R1RqaHRuSTMrTDVaZ0NxClV2NXZDbmwvSkJLbWU4ZU84VXdHT0ltbThMT1VnZHlkSWFabEN6c3Q4dE9iMWRHdnRUanB6SEVmRmxkSTNuOHYKSmNGbUg2MGFSQjgzRlhNMTd4WHcrRVBubXVSeE9iV2toSkVsV2dDQ1BSTFNHaG51MzAwR1hmNWNxZGVFMUszMQpRNCtHalNXaW5sTnZ0aHNXV3JrbmN3ZWFIYTVNQTI4alJpQm5zbUpRVzRUWU0yaUY1anlpZDRDMGdqeVI4dzd5CjFVTHRJcWJzOGdudS9kTXlxcXNhWG53L1RHaFVaNEJ1bTRFdjk3cnF4dDhWTEd6ZldmMEloMGYwSFBNM01UUlEKc0hvSy84ZEFmNllqYjlHUXZWdWhRcnJCcGt0UUdzcnEyaHlsVmppdWUya3VvNWJUcUhKK2FrWjhmRWVoVCswNgpoMkF3Y3hKQWxkYnFObDB5Qzlzd1FqTTVETjJZYVJGa3drVDhZcEpnYzBXZEF5UlNsQ2l0RmIzelk1ZjJ3ckV4CjM1MjNOTTNhVXNNTHIxOGhqb2JDRnVtbEhxYmp4d3piY1IxdXFSYVlPQlRyZGV6Q2E2RGo3eWJLWXJQVTdSMTEKd0FwbVFUdFNyN3dyRjlTZDVmUFRuYVdhSlF0OTMvT2pWR1JkbVFyWHorRGRIMTR0WjhrR3VUVmsyZ0RZUmd5agpuRjF1SWVRNGpQeGVra2NzQlRDMERsTHBRYnlIWWo5N2d5cndjUmZFRS9RMHRWUHVxYnp0cUpYQytETVZsTlU3CnkwRWNtOCtkMEJwbWpxbnB3akRxSnpYMWxUQTVqcWNibjJuRlMvZXpSeU1ydVAyRlFMaXlpWWRMeHVKbnRyOEkKcEg0OXRKS3gvVzcrTWJnaWlKeE1UcDNwSy9HdFdEbUxkRFU5TzZjcG8wb2tOUitKNVUzT1pMZlhMdlBrY2cySApRZHdEcGdoZzBNSVNjMG9GNmVrZkdSNXBrRW9sdzQ2L3hTRDMwTEdtV2pPS0c2UTN3S3UxWjE5UzNGVTRJemVmCkE3RCtEckRyd2J1ODlkNEpLZW43UUhjOFJRWnRha0c1UUhNcXFNUUZYZWh5VE84ZzVJcGp4VGN3c0w0ek9QZkcKdzVKdHQwRlNVU21GRmwyK0NXUkwyWC9SU3lCcUJicE9OaktFOXhjb2lZRG5CcmZnQkZBcDduZ3d5cWxZSnRpTApwODFvRFNJOVpLYU1QeGtJNmRadUlDWlRTeTJTRkRyaVdaWEVrVUVGenBYNi9ZS21VMy9oWkVsV1pnTFJYeldKCnN6K2JwUWg5RFp1eWVZbTY5MFNwRm9nL3VxclE2NFRUR0xoc3YyaGdER09tV09TQUcreFNYUzEzajFvYjlITFQKZ0FyUVF0M3BqZEFTTEg2WjRXM2Jyclc5a1EvZlZtMnE0Q25YdTQ3YnZ4Wjh6L3VvTkloRGxqQVVCZ05WSFVrRQpEVEFMQmdsZ2hrZ0JaUU1FQXhJd2dnejdCZ05WSFVvRWdnenlBNElNN2dEQXBrU0xwc1hBVzFqeFFhN2lENVZTCnJXL0RKdWlUUXRmVGt0NWovbWFLNDdNMmtqbDlwRDJBZGtPYzh1dmJ3WEsrZHFHaWdUTUtxREk4UTAxdnhDOGUKZzhZTnZHZWRwU21odVE5bG1jSzBTU0RPTnk0NlE3aU15OHlaa0NRNjg1bTNaeGdyNXBFTkNUZElBZG9TUFZCSQpWOFU1VnNlRUNwSEFJTVhNK1JlcnhVV3NEakdoNWY4MEdkVHdtY1lSaC85emRUNTl6R3R4aWltSmNjcU5KNGo5CmN5ZkZFbmgySmRJNmJ3UnRnUzVpeVhJN0hJeGJhZEZqc09IMVlYYWxWdFV5SThZcitUc01WT2xYQWtuN1c3WW4Kb3RQNTBqR2luTEdibUswa2NKOFdHTzhScWJkcGZxUHBFSGIwT3B6OHdxSytGeGdBT1ZzakNPN1lhaTdjTHcxTwp5eUdEUHNYeEo3R0R6dXVHQUpmeTV0elNMMnh4MFBKRFdza3F1SDlQaXQrRFFSTnl6WlhIV1JObmFtSUE1RG5zCmRaNFJuYUkwUWlic3EycFRacnZaa0hUcDU0ZmVkQU05V3huMTZrZkRXZk5GcXRvSFBvNDIrMkFibzI1bjFUc0wKUHNXdktxdkpzR0d3ZmIxWTIzelFyVGl5QlUrVytEY2VraUtCYXJJaFVXTGp4UDRXNWhXUWFNWDJBM2xEakNocApLRWt0c0dQL3lXWk95NTZVUTRrSm96R0xsOG1TSlJoS25zMWQ4Z2YwUW1icTl1N3VwSUVXUzdXU1FXTUd4SDZGCjN1MFNwcjhFdlZPTlZHWW85RWp3T0NhVytqZEU5eGxPUDVVYS96S3dSRDJNQ3pFcXgwd1k3cEoreURFSGdsUVoKRUFpRFFGSW1CNG16N3ExdWFIcWVYNmEwbVpPZEIyS09QekswbE5FMnI0S09QdHE3YlhCVjRmZWFRTWlKaDc0SAp0TUJyQ3BjdGkzK2h3N1BCMGVtV3BRZEx4R0lpdEozSTVTb09JTVRLaTFQSTloN042bUZSYzBsd0NVT2l2ZURyCnZpLzdvVGt5TG1aNTAyR2xKbHNpTWlrMDRrOW00NW5PSXRjNkFvYkw5UjUxRlZTVC9jeTh3QUFFNGlXaW5iQlYKNnlwNTk3U29HS05iQ0xYTzh4VkJUdnhpdUlHQmFSVEZ0aXpWUmUwOWIrVmtDaTVZZG84SFNEK0I0L2U5WWhJcQplRmo0UEZvZ1JPeGhrdHFwUFFIRHcrOGZlRVczQy9pOVAyVCtIU3NxaDk1ZXB2eExjeDlXcUFuSFZNZFllcDVIClduell2QjZDbzFQR0tVWTJaK3JHTVBpUEhVR0VlY1FKUnRpSTUwQlB5LzBqSFBMRktnbW1Mb3RhVTllMjlZY1AKK2hVTkhxWU94eTJwRStUejRFbzBjSGtlNGVROHE5ZWpaSG1jU2J0YnVaTUxEVm9yaVNkQ2s0K283a0FKU3ZIYwpBdjA4VXhMeFRUT2Q2S1o4M0pLV3VUUlo4MWtVVmFOdjRmckNodWpia1JYODQvUzJoYUtEREpzSkpteWVRUm9QClZTOFVQcjh4dG4ydm9OcWR5U3Uzdnh3emZUZGdWVTJzdFplM2hDK21sV0pHT2E1VWtpVGtFRE9MdVdvV3pzYTIKQ1U0VXpsMC9FRU1HY0tPMi9iY0FHU0ZqQTNKblRHblhjSmdUdXA3SHJ4dlliaTZIaW4vVFFZSkg2d1I3OFg5eQp2Qk1jVFBjalhFQ2N2enhySjlkYVR0N2F1TXB4azNSMFJOclZpR3R3dlJlSGxLNElSUzE4UEFxZFJzcVExUGg2ClRyT1QrYlgxRVd3ZlRUdWlVZnBZL01hbU9NTTdLOXh2MFZ2Z05ENmpuUUU3QkRaVk1VM3RlSnJjSjRHeVB6QU4KdFhTdmh0VjlsOERyU1hHRTRWb0hmMzFBZldHc20wV05VRGh2c0d1a2htc0ViKzR6ajR2TitYYjNTVlBYQitqaQpBSnZiNjdLRWJLQUMzMExLRTVUOHFFSjBjNUZSSnBBTDdEaWRSUFNuZDNxcHhNWDBkbU5vV0VZUWttZ2MxU0RSCkZGTmNjNjZhMFljeWF2dVJnSjRPZk1JN0lFZytINm9YQ01xUGRNT3FVTEJTcG5ZZzdLb1A0QTNvcjJKQmtTeHcKcUpjTTNvejBZeWtIalpZK1lZMjhteUI0NFd4T1hBalV6NUF3akx4c3l5M2QwYUZaZVVnTnB5ekt5RzZlQmJzSQp3K1NrZC9mRnFyOXJkM1NDVEFuaUdTY2lxZVcreTBwUVVMbEk2bUx5OGlKaGpPcWVqckdHL2VTMndpNzQwSVk2Cmk0ZUt4TWdoLzYveGdiN2dQcCtvK1VudHhMK3dlYjRLYWV2N2NPZkFnUndJRmRxTHBLZWhhWFhmbVNTK2FlOUsKOWExSmJzUVJaTzdPS2RacGIvQVQ5UWhLc2E4MlpGRWY1aGdqUDBoWW1hdDRyRmpuYU0xNzZvZnFlVUc5dmJSQwpXaTVFaitpMk5RekkzN3VzbEJMN1BGNzMzZmY1Mml5SmtGRS90S1o3NDk4ZnF2OEdEMW5DdVJBbE9nVDlIREN1CkpGUnpMc3ZJWUE1dGMwWTUvNkwwNnVpRUoyMllYakZjam9NbXpiUHhDR2padENyZm56Z2xMdFRIRU16bXI4WGoKQ1IyTG5pMEhObWwwaXYxOXRqYlYyVzViQXRVUHNaMnp5QUQrU1ZiV2tyY3F3OGN3ektjSGdZZHlYNVZXY1VkZwpWbTViaTVTRlBKSnFjRWlrMGRpTHAxZ3NuVGlRSm5US3Ztck94Y1Izam5YQVFzU1Z5ZnJUTWhKNE5LYWRKdlhiCkw0K1psNzdsV2dFM04vRFBya2g0b2RSNVlIL1luaWt5d2JXdGpzSURkN0xhUW5yVUpsSnh6bHNWOC9WRzBWYnkKZmg4Rmh1TWpYWTJ4SmVvWWFZRDlnVlBReFVrTGlZN1FnVHBPRE9OTDJ2UUhEcGg1ZENZc2pTTE84cXZ5SGRpNAo1R3ptVkppbE1GdnZTZzM1dXpKY0lwSVhhZ2hxcEp6NnZ4eDRiMzBubWg5SGpEbGVPdmEvdlhFQm1LclB2WldnClF4WjJGNHQ3L2s1TERjMS9zalVNOURjMW83T1JITFZTckVzZGJwUnR5YTJnQkcyQXF0V0lSVW5GWTZ1RjZNUEoKZnBZVmJRYm9NZ3p0OGJYUS9CSDhhRlA4WFpPbzA1b0F2Zk4xbHJkajJkUkkrUTJldllSR0hmaTEwZkc0UVhUVgpoREUyOFBoTXNiYTRzTGlDaEt5ejBGcndkbEtDbVpqdzdkc3JuYlVkclpkTTVmdkpreWIvYmZkTmkyK3h4enplCk5OMkxaZDJMWUxDSFo5bHNvUzVsTS80dTFLLzUwYXVrcnhUUkJhbUVTT0ZOTmJuRWZ2MDd0WlRJUWRHOWlJTGQKZk8wWlAwTUdENERDcENtcmpJZGUzZ216YzNidDhWVFJvMHU4VW5pS2xHTlJDclZVR3JmWWdnTmVKVkNINDdqVgpWenhhdFAwbDFnalNLd0UrM0VnUyszc3l5eElFcFlvNndweTJKcnd1S0xrREFTOVVicFFCODZnRExaUldHRjBZCjFqdzJOeUxnMDhIUDB3OGdjYzNPb0VEcnlORjFidVAvNVRFVkRqMkRmdFphaGxxYzhuaStOUDJRUTFUM3BqK3MKV0NqaVhDcGJMVnpHSHhHYlRMUzdMaG53bXgyNVBzNjAvUGx1ZTExa1o2TG5jcGZYLzJDZFpXbnNzZFJtVDJBUgpVeXVsSjBWRlp4N01wNXEwMVNyZ29oTDlSSlRaSEVYRWRKTlJTRVRFdWF2eEd1RjRackVScXlZZENEeUNWNFZxClk3V21hUy9JNTFrUjY5b2RMN0lCdjNXWnpCNG5EbXRtbW9ERS9nNDJnQXUvTXhaMTd5M3ZKT0xFbnVsMWt3bHoKNGhWcVo0ZnJxd1B5VlJVM1plemZYM0tLRXUwdVhIczI4NlpmMm5kQjFwTEFQUkYybE1mcFJJcmp2THBkQlBxNAo2RS82OGxHYTA1VlA2aGVNSmFON3dTRCtYUTlJaDcxS3kyaWdlcXB3N2VFMnZobHFUQXBPK1BQMXpIaUZWV2tECnlOWXhRYitIR0YyMzZZbjNxTG9wYVJFMkovbG52bnQyendWTm1ZQ3pvN3FSMytVN0pMYUNVVGRRc2J5NlhOb0YKVnNDa3pGZmJQNFVuYlZiQit1WDBJVFhhYVB6TnNiTE16d09oMFUreWxiRVphdkNpNFQ0SGpSQThPT29MK2MvYgpoK0ZORk9yVEExL3V0cU40bXVSY0JmRWw3Z2NGTGZUWm1PUXNrYkNoejR0cUlKYmkzN1FhL29rOU9qWWFzaGpuCitTTFRSbTVENDNJYWNTK1BBMnFWd2pubnF2c0dPUDhQOW1sM0VoM3NvSjlZL0g0OW9TWUNXZDhlVVdxVG1WOVoKZ05FdGFPaHh2VU1pbDhaKytYMWlmeXFLMEF5SFVLMVQ4MHdhM3Zvc2dhc1hKR0VpUzRQdDNPUmQyWjJDYzRDVAovajF3bjA1VENQK2l1bjNtM041T25wdGRYWGoxcGNCcGFucllJR3J0OVZPdlNQMDdNWTJoZXlCWVpyZmVyWUlTCnhNaWxqSERVRjZhc3pGc3p5elJVTzdhMm93M2Jmd1NGU3NjdkczSkMwQXFpbDFMb2R5RDF5c0o3bU9aTFFLSTUKeVJkMEhsNEJxSnpIRjdCRUxwYXNGOVBPYStHNm9SY1BrSUl5aXlvd3BKSzArdk5ZR3JINTl4blhCV3ZrYlNMSwpEc0s1S2xrenN4Z081K08rSFZuakU0d0dITjlTSDY3Y0R6Y0V2UVdJREIzSVNkUEs5QWJBNXBFUC9iamRNeDRsClhISmphSWpBaWtQRXIwV0xUdHRsUUVycTU3YkVaeCtGdVZZdldKcVBKSENzcHZ0aWVkeG8xakt6Q1VXUHRRMDIKRGpKQzVUV1hCTExnaTR5bmlCWWU2UUdDdG5wOWhDZXIraUdoRkQzNStkNm0vQzVHaWpZT0NIeHR5N1BNVUZpcwpZL3NKZWNQNU5KQURxWlNZSHRNMlF6b0x5TzFnbTlEQUc2bXh5eHdpL0ZJZHVmaGFuS1NhQ2Z6N2V6bW0vZU5oCkFGcEpaK2VSZDRqSnFCOHN0Wm5WNE4rQXVwcmFPeUdRSEZqeXpQeHRROVBubkYxQVhBNW9JOWNkaURvRTRLaWEKTmVoemtNbXJwT3RicTRaU29GcXhQUXpkaHh0NzdmMmdTeTJ1aTVRS2FZTnd6cWxBQlBydHFNa2tFaURNWjNWLwptRVNXYUttTVNrTXdmWUwyQTUyUXd4Zm54V1I3TTJFR00rN2FkV2dqMlQwWEFPaVJYcldadXlCSnlMRXlRSTdUCktEaFhIenBmenFnTXptL0tUYVhsWGlPYlVSTDEwS2JZZ3ZFZ3BjTFdMeW1rOGYxRDFUMjVkVU9jRTd5MWpRazgKTytDSGZoME9BaENtUm5JTENLejZkdU1IYk9Zc3BpY2s2WEI4a3hFYmtXMzBSZksxNTQ2U3JQd2U3N3NER1JXeApHTmZTYTNaaGU1ZUMvbG40emZYaGlRN3ZMWEk4YlJ2K082dzdHSVRkUzRpd095a3BZTGtmQ1d5OWdha1lKYjdwCmg0ZVdyb3dNWHdRMVVsNVZCMlZLUHc2RUxkei9ha1lwbkNGN0lLYU9uNmVOR2lBNFVqMlVSTkZUM3VVb1VNWm0KZW01Slg3R3oyVktDWDl2Rld6Q1N4WWFjdmRYaThnYXcyaGdkTkZ0NHRyZTQxdUNuNXg5RmJIMk8xL0lpUEVKagpvTG02eGREU0FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBR0NSTVZIQ1l3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCkFGYk4zbW1xTERNQkRQZXBTQ0c1WHlHYmI5NmZsVzNRYVNLVm9tc090WDBVNDZDNmZOeXdGaE5BVkd2VnFRancKY0hDOG9qUEdiazFWejdXSTFBb1NsSlhXRmhrQzYyQVVnOTl4aTRPVjFLZVhTL29CU1VHNEJaeXdjUFQveEhIRQpMTnhHc21MRzhrZVhPa29Ta3FSR2haNWxVeDZocTdjcmVTNGVBZ2ZrOEh1RnBackxyRm1MTjFURWRmdUFoK0RHCkJkR3BieWQwenJsN3pjaGJsTjZSQlEwQmwrRDlqTDdzbTRTVllnRzhUellpd3FWcmkxZHlIRnFyUFlmdzE2TW0KRTBudjc2bVdWTW53dkdCc2w3M1FCM0wvLzUrSU85TjVJbUd6aEJ0eDdITFU3V1ExZDlUSDNtYTFWYWlmSlE0LwpUM0VuWElpSFNnY3BiY1V2M3dNdUR5Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==";
    private static final int AUTH_SERVICE_MOCK_PORT = 10000;

    @DynamicPropertySource
    static void authServiceProperties(DynamicPropertyRegistry registry) {
        registry.add("auth-service.base-url", () -> "http://localhost:" + AUTH_SERVICE_MOCK_PORT);
    }

    private static final String SAMPLE_PKCS10 = "MIIBUjCBvAIBADATMREwDwYDVQQDDAhuZXdfY2VydDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA52WsWllsOi/XtK8VcKHN63Mhk6awMboP9iuwgtPXzkFLV/wILHH+YPAJcS8dP037SZQlAng9dF+IoLHn7WFYmQqqgkObWoH1+5LxHjkPRRNPJLKPtxfM/V+IafsddK7a5TiVD+PiKjoWQaGHVEieozV1fK2BfqVbenKbYMupGVkCAwEAAaAAMA0GCSqGSIb3DQEBBAUAA4GBALtgmv31dFCSO+KnXWeaGEVr2H8g6O0D/RS8xoTRF4yHIgU84EXL5ZWUxhLF6mAXP1de0IfeEf95gGrU9FQ7tdUnwfsBZCIhHOQ/PdzVhRRhaVaPK8N+/g1GyXM/mC074u8y+VoyhHTqAlnbGwzyJkLnVwJ0/jLiRaTdvn7zFDWr";

    @Autowired
    private CertificateService certificateService;
    @Autowired
    private CertificateRepository certificateRepository;
    @Autowired
    private CertificateContentRepository certificateContentRepository;
    @Autowired
    private RaProfileRepository raProfileRepository;
    @Autowired
    private AuthorityInstanceReferenceRepository authorityInstanceReferenceRepository;
    @Autowired
    private ConnectorRepository connectorRepository;
    @Autowired
    private FunctionGroupRepository functionGroupRepository;
    @Autowired
    private Connector2FunctionGroupRepository connector2FunctionGroupRepository;
    @Autowired
    private GroupRepository groupRepository;
    @Autowired
    private GroupAssociationRepository groupAssociationRepository;
    @Autowired
    private ResourceObjectAssociationService associationService;
    @Autowired
    private OwnerAssociationRepository ownerAssociationRepository;
    @Autowired
    private CryptographicKeyRepository cryptographicKeyRepository;
    @Autowired
    private CryptographicKeyItemRepository cryptographicKeyItemRepository;
    @Autowired
    private AttributeService attributeService;
    @Autowired
    private AcmeProfileRepository acmeProfileRepository;
    @Autowired
    private ProtocolCertificateAssociationsRepository protocolCertificateAssociationsRepository;
    @Autowired
    private CertificateRelationRepository certificateRelationRepository;

    private AttributeEngine attributeEngine;

    private Certificate certificate;
    private RaProfile raProfile;
    private Group group;

    private X509Certificate x509Cert;

    private Connector connector;
    private WireMockServer mockServer;

    @Autowired
    void setAttributeEngine(AttributeEngine attributeEngine) {
        this.attributeEngine = attributeEngine;
    }

    @BeforeEach
    void setUp() throws GeneralSecurityException, IOException, AttributeException {
        mockServer = new WireMockServer(0);
        mockServer.start();

        WireMock.configureFor("localhost", mockServer.port());

        connector = new Connector();
        connector.setName("authorityInstanceConnector");
        connector.setUrl("http://localhost:" + mockServer.port());
        connector.setStatus(ConnectorStatus.CONNECTED);
        connector = connectorRepository.save(connector);

        FunctionGroup functionGroup = new FunctionGroup();
        functionGroup.setCode(FunctionGroupCode.AUTHORITY_PROVIDER);
        functionGroup.setName(FunctionGroupCode.AUTHORITY_PROVIDER.getCode());
        functionGroupRepository.save(functionGroup);

        Connector2FunctionGroup c2fg = new Connector2FunctionGroup();
        c2fg.setConnector(connector);
        c2fg.setConnectorUuid(connector.getUuid());
        c2fg.setFunctionGroup(functionGroup);
        c2fg.setFunctionGroupUuid(functionGroup.getUuid());
        c2fg.setKinds(MetaDefinitions.serializeArrayString(List.of("ApiKey")));
        connector2FunctionGroupRepository.save(c2fg);

        connector.getFunctionGroups().add(c2fg);
        connectorRepository.save(connector);

        AuthorityInstanceReference authorityInstance = new AuthorityInstanceReference();
        authorityInstance.setName("testAuthorityInstance1");
        authorityInstance.setConnector(connector);
        authorityInstance.setConnectorUuid(connector.getUuid());
        authorityInstance.setKind("sample");
        authorityInstance.setAuthorityInstanceUuid("1l");
        authorityInstance = authorityInstanceReferenceRepository.save(authorityInstance);

        CertificateContent certificateContent = new CertificateContent();
        certificateContent.setContent("123456");
        certificateContent = certificateContentRepository.save(certificateContent);

        RaProfile raProfileOld = new RaProfile();
        raProfileOld.setName("Test RA profile Old");
        raProfileOld.setAuthorityInstanceReference(authorityInstance);
        raProfileOld = raProfileRepository.save(raProfileOld);

        certificate = new Certificate();
        certificate.setSubjectDn("testCertificate");
        certificate.setIssuerDn("testCercertificatetificate");
        certificate.setSerialNumber("123456789");
        certificate.setState(CertificateState.ISSUED);
        certificate.setValidationStatus(CertificateValidationStatus.VALID);
        certificate.setCertificateContent(certificateContent);
        certificate.setCertificateContentId(certificateContent.getId());
        certificate.setIssuerCertificateUuid(UUID.randomUUID());
        certificate.setRaProfile(raProfileOld);
        certificate = certificateRepository.save(certificate);

        // Ensure OwnerAssociation is created and associated
        OwnerAssociation ownerAssociation = new OwnerAssociation();
        ownerAssociation.setOwnerUuid(UUID.randomUUID()); // Set a proper UUID
        ownerAssociation.setOwnerUsername("ownerName");
        ownerAssociation.setResource(Resource.CERTIFICATE);
        ownerAssociation.setObjectUuid(certificate.getUuid());
        ownerAssociation.setCertificate(certificate);
        ownerAssociationRepository.saveAndFlush(ownerAssociation);

        certificate.setOwner(ownerAssociation);
        certificateRepository.save(certificate);

        List<MetadataAttribute> meta = new ArrayList<>();
        MetadataAttributeV2 tst = new MetadataAttributeV2();
        tst.setType(AttributeType.META);
        tst.setName("Test");
        tst.setContentType(AttributeContentType.STRING);
        tst.setUuid("9f94036e-f050-4c9c-a3b8-f47b1be696aa");
        MetadataAttributeProperties metadataAttributeProperties = new MetadataAttributeProperties();
        metadataAttributeProperties.setLabel("Test meta");
        tst.setProperties(metadataAttributeProperties);
        tst.setContent(List.of(new StringAttributeContentV2("xyz", "xyz")));
        meta.add(tst);

        UUID connectorUuid = raProfileOld.getAuthorityInstanceReference().getConnectorUuid();
        attributeEngine.updateMetadataAttributes(meta, new ObjectAttributeContentInfo(connectorUuid, Resource.CERTIFICATE, certificate.getUuid()));

        raProfile = new RaProfile();
        raProfile.setName("Test RA profile");
        raProfile.setAuthorityInstanceReference(authorityInstance);
        raProfile = raProfileRepository.save(raProfile);

        group = new Group();
        group.setName("TestGroup");
        group.setDescription("Test group description");
        group.setEmail("rybanoha@example.com");
        group = groupRepository.save(group);

        InputStream keyStoreStream = CertificateServiceTest.class.getClassLoader().getResourceAsStream("client1.p12");
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        keyStore.load(keyStoreStream, "123456".toCharArray());

        x509Cert = (X509Certificate) keyStore.getCertificate("1");
    }

    @AfterEach
    void tearDown() {
        mockServer.stop();
    }

    @Test
    void testListCertificates() {
        // Prepare
        GroupAssociation groupAssociation = new GroupAssociation();
        groupAssociation.setGroup(group);
        groupAssociation.setGroupUuid(group.getUuid());
        groupAssociation.setResource(Resource.CERTIFICATE);
        groupAssociation.setObjectUuid(certificate.getUuid());
        groupAssociationRepository.saveAndFlush(groupAssociation);

        certificate.setGroups(Set.of(group));
        certificateRepository.save(certificate);

        // Act
        CertificateResponseDto certificateEntities = certificateService.listCertificates(SecurityFilter.create(), new CertificateSearchRequestDto());

        // Assert
        Assertions.assertNotNull(certificateEntities);
        Assertions.assertNotNull(certificateEntities.getCertificates());
        Assertions.assertFalse(certificateEntities.getCertificates().isEmpty());
        Assertions.assertEquals(1, certificateEntities.getCertificates().size());

        CertificateDto dto = certificateEntities.getCertificates().getFirst();
        Assertions.assertEquals(certificate.getUuid().toString(), dto.getUuid());
        Assertions.assertEquals(CertificateUtil.formatCommonName(certificate.getCommonName()), dto.getCommonName());
        Assertions.assertEquals(certificate.getSerialNumber(), dto.getSerialNumber());
        Assertions.assertEquals(certificate.getIssuerCommonName(), dto.getIssuerCommonName());
        Assertions.assertEquals(certificate.getIssuerDn(), dto.getIssuerDn());
        Assertions.assertEquals(certificate.getSubjectDn(), dto.getSubjectDn());
        Assertions.assertEquals(certificate.getNotBefore(), dto.getNotBefore());
        Assertions.assertEquals(certificate.getNotAfter(), dto.getNotAfter());
        Assertions.assertEquals(certificate.getPublicKeyAlgorithm(), dto.getPublicKeyAlgorithm());
        Assertions.assertEquals(certificate.getAltPublicKeyAlgorithm(), dto.getAltPublicKeyAlgorithm());
        Assertions.assertEquals(certificate.getSignatureAlgorithm(), dto.getSignatureAlgorithm());
        Assertions.assertEquals(certificate.getAltSignatureAlgorithm(), dto.getAltSignatureAlgorithm());
        Assertions.assertEquals(certificate.isHybridCertificate(), dto.isHybridCertificate());
        Assertions.assertEquals(certificate.getKeySize(), dto.getKeySize());
        Assertions.assertEquals(certificate.getAltKeySize(), dto.getAltKeySize());
        Assertions.assertEquals(certificate.getState(), dto.getState());
        Assertions.assertEquals(certificate.getValidationStatus(), dto.getValidationStatus());
        Assertions.assertEquals(certificate.getFingerprint(), dto.getFingerprint());
        Assertions.assertEquals(certificate.getOwner().getOwnerUsername(), dto.getOwner());
        Assertions.assertEquals(certificate.getOwner().getOwnerUuid().toString(), dto.getOwnerUuid());
        Assertions.assertEquals(certificate.getCertificateType(), dto.getCertificateType());
        Assertions.assertEquals(certificate.getIssuerSerialNumber(), dto.getIssuerSerialNumber());
        Assertions.assertEquals(certificate.getComplianceStatus(), dto.getComplianceStatus());
        Assertions.assertEquals(certificate.getIssuerCertificateUuid().toString(), dto.getIssuerCertificateUuid());
        Assertions.assertEquals(certificate.getTrustedCa(), dto.getTrustedCa());
        Assertions.assertEquals(certificate.isArchived(), dto.isArchived());
        Assertions.assertFalse(dto.isPrivateKeyAvailability());
        Assertions.assertNotNull(dto.getRaProfile());
        Assertions.assertEquals(certificate.getRaProfile().getName(), dto.getRaProfile().getName());
        Assertions.assertNotNull(dto.getGroups());
        Assertions.assertEquals(1, dto.getGroups().size());

        Group expectedGroup = certificate.getGroups().stream().toList().getFirst();
        GroupDto actualGroup = dto.getGroups().stream().toList().getFirst();
        Assertions.assertEquals(expectedGroup.getUuid().toString(), actualGroup.getUuid());
        Assertions.assertEquals(expectedGroup.getName(), actualGroup.getName());
        Assertions.assertEquals(expectedGroup.getDescription(), actualGroup.getDescription());
        Assertions.assertEquals(expectedGroup.getEmail(), actualGroup.getEmail());
    }

    @Test
    void testListCertificates_emptyDueToPermission() {
        OpaObjectAccessResult objectAccessDenied = new OpaObjectAccessResult();
        objectAccessDenied.setActionAllowedForGroupOfObjects(false);
        objectAccessDenied.setAllowedObjects(List.of());
        objectAccessDenied.setForbiddenObjects(List.of());

        Mockito.when(
                opaClient.checkObjectAccess(Mockito.any(), Mockito.any(), Mockito.any(), Mockito.any())
        ).thenReturn(objectAccessDenied);

        CertificateResponseDto certificateEntities = certificateService.listCertificates(SecurityFilter.create(), new CertificateSearchRequestDto());
        Assertions.assertNotNull(certificateEntities);
        Assertions.assertNotNull(certificateEntities.getCertificates());
        Assertions.assertTrue(certificateEntities.getCertificates().isEmpty());
        Assertions.assertEquals(0, certificateEntities.getTotalItems());
    }

    @Test
    void testListCertificates_missingFields() {
        ownerAssociationRepository.delete(certificate.getOwner());
        certificate.setOwner(null);
        certificate.setKey(null);
        certificate.setKeyUuid(null);
        certificate.setRaProfile(null);
        certificate.setRaProfileUuid(null);
        certificateRepository.saveAndFlush(certificate);

        CertificateResponseDto certificateEntities = certificateService.listCertificates(SecurityFilter.create(), new CertificateSearchRequestDto());
        Assertions.assertNotNull(certificateEntities);
        Assertions.assertNotNull(certificateEntities.getCertificates());
        Assertions.assertFalse(certificateEntities.getCertificates().isEmpty());
        CertificateDto dto = certificateEntities.getCertificates().getFirst();

        Assertions.assertNull(dto.getOwner());
        Assertions.assertNull(dto.getOwnerUuid());
        Assertions.assertNotNull(dto.getGroups());
        Assertions.assertNull(dto.getRaProfile());
        Assertions.assertTrue(dto.getGroups().isEmpty());
        Assertions.assertFalse(dto.isPrivateKeyAvailability());
    }

    @Test
    void testListCertificates_privateKeyAvailable() {
        CryptographicKey key = new CryptographicKey();
        key.setName("testKey");
        cryptographicKeyRepository.save(key);

        CryptographicKeyItem item = new CryptographicKeyItem();
        item.setKey(key);
        item.setType(KeyType.PRIVATE_KEY);
        item.setState(KeyState.ACTIVE);
        item.setName("testItem");
        cryptographicKeyItemRepository.save(item);

        key.getItems().add(item);
        cryptographicKeyRepository.save(key);

        certificate.setKey(key);
        certificateRepository.saveAndFlush(certificate);

        CertificateResponseDto certificateEntities = certificateService.listCertificates(SecurityFilter.create(), new CertificateSearchRequestDto());
        Assertions.assertNotNull(certificateEntities);
        Assertions.assertNotNull(certificateEntities.getCertificates());
        Assertions.assertFalse(certificateEntities.getCertificates().isEmpty());
        CertificateDto dto = certificateEntities.getCertificates().getFirst();

        Assertions.assertTrue(dto.isPrivateKeyAvailability());
    }

    @Test
    void testGetCertificate() throws NotFoundException, CertificateException, IOException {
        CertificateDetailDto dto = certificateService.getCertificate(certificate.getSecuredUuid());
        Assertions.assertNotNull(dto);
        Assertions.assertEquals(certificate.getUuid().toString(), dto.getUuid());
        Assertions.assertEquals(certificate.getSerialNumber(), dto.getSerialNumber());
    }

    @Test
    void testGetCertificate_notFound() {
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.getCertificate(SecuredUUID.fromString("abfbc322-29e1-11ed-a261-0242ac120002")));
    }

    @Test
    void testCreateCertificateEntity() {
        Certificate cert = certificateService.createCertificateEntity(x509Cert);

        Assertions.assertNotNull(cert);
        Assertions.assertEquals("CLIENT1", cert.getCommonName());
        Assertions.assertEquals("177e75f42e95ecb98f831eb57de27b0bc8c47643", cert.getSerialNumber());
    }

    @Test
    void testCreateHybridCertificate() throws InvalidAlgorithmParameterException, CertificateException, NoSuchAlgorithmException, SignatureException, InvalidKeyException, OperatorCreationException, IOException, AlreadyExistException {
        Certificate hybridCertificate = certificateService.checkCreateCertificate(Base64.getEncoder().encodeToString(
                CertificateTestUtil.createHybridCertificate().getEncoded()));

        Assertions.assertTrue(hybridCertificate.isHybridCertificate());
        Assertions.assertNotNull(hybridCertificate.getAltSignatureAlgorithm());
        Assertions.assertNotNull(hybridCertificate.getAltKeyUuid());

        Optional<CryptographicKey> altCryptographicKey = cryptographicKeyRepository.findByUuid(hybridCertificate.getAltKeyUuid());
        Assertions.assertTrue(altCryptographicKey.isPresent());
    }

    @Test
    void testCheckCreateCertificate() throws CertificateException, AlreadyExistException, NoSuchAlgorithmException {
        Certificate cert = certificateService.checkCreateCertificate(Base64.getEncoder().encodeToString(x509Cert.getEncoded()));

        Assertions.assertNotNull(cert);
        Assertions.assertEquals("CLIENT1", cert.getCommonName());
        Assertions.assertEquals("177e75f42e95ecb98f831eb57de27b0bc8c47643", cert.getSerialNumber());
    }

    @Test
    void testAddCertificate_certificateException() {
        Assertions.assertThrows(CertificateException.class, () -> certificateService.checkCreateCertificate("certificate"));
    }

    @Test
    void testRemoveCertificate_notFound() {
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.deleteCertificate(SecuredUUID.fromString("abfbc322-29e1-11ed-a261-0242ac120002")));
    }

    @Test
    void testRevokeCertificate() throws NotFoundException, CertificateException, IOException {
        certificateService.revokeCertificate(certificate.getSerialNumber());

        CertificateDetailDto dto = certificateService.getCertificate(certificate.getSecuredUuid());

        Assertions.assertNotNull(dto);
        Assertions.assertEquals(certificate.getUuid().toString(), dto.getUuid());
        Assertions.assertEquals(certificate.getSerialNumber(), dto.getSerialNumber());
        Assertions.assertEquals(CertificateState.REVOKED, dto.getState());
    }

    @Test
    void testUploadCertificate() throws CertificateException, AlreadyExistException, NoSuchAlgorithmException, NotFoundException, AttributeException {
        UploadCertificateRequestDto request = new UploadCertificateRequestDto();
        request.setCertificate(Base64.getEncoder().encodeToString(x509Cert.getEncoded()));

        CertificateDetailDto dto = certificateService.upload(request, true);
        Assertions.assertNotNull(dto);
        Assertions.assertEquals("CLIENT1", dto.getCommonName());
        Assertions.assertEquals("177e75f42e95ecb98f831eb57de27b0bc8c47643", dto.getSerialNumber());

        // test for presence of created public key
        var newCertificate = certificateRepository.findWithAssociationsByUuid(UUID.fromString(dto.getUuid()));
        Assertions.assertTrue(newCertificate.isPresent());
        Assertions.assertEquals("certKey_%s".formatted(dto.getCommonName()), newCertificate.get().getKey().getName());
        Assertions.assertEquals(1, newCertificate.get().getKey().getItems().size());
        Assertions.assertEquals(KeyType.PUBLIC_KEY, newCertificate.get().getKey().getItems().stream().findFirst().get().getType());
    }

    @Test
    void testUpdateRaProfile() throws NotFoundException, CertificateOperationException, CertificateException, IOException, AttributeException {
        mockServer.stubFor(WireMock
                .post(WireMock.urlPathMatching("/v2/authorityProvider/authorities/[^/]+/certificates/identify"))
                .willReturn(WireMock.okJson("{\"meta\":[{\"version\": 2,\"uuid\":\"b42ab690-60fd-11ed-9b6a-0242ac120002\",\"name\":\"ejbcaUsername\",\"description\":\"EJBCA Username\",\"content\":[{\"reference\":\"ShO0lp7qbnE=\",\"data\":\"ShO0lp7qbnE=\"}],\"type\":\"meta\",\"contentType\":\"string\",\"properties\":{\"label\":\"EJBCA Username\",\"visible\":true,\"group\":null,\"global\":false}}]}")));

        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setRaProfileUuid(raProfile.getUuid().toString());

        certificate.setArchived(true);
        certificateRepository.save(certificate);

        UUID oldRaProfileUuid = certificate.getRaProfileUuid();
        SecuredUUID certificateSecuredUuid = certificate.getSecuredUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.updateCertificateObjects(certificateSecuredUuid, uuidDto));
        Certificate certificateReloaded = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertEquals(oldRaProfileUuid, certificateReloaded.getRaProfile().getUuid());

        certificate.setArchived(false);
        certificateRepository.save(certificate);

        certificateService.updateCertificateObjects(certificateSecuredUuid, uuidDto);

        certificateReloaded = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertEquals(raProfile, certificateReloaded.getRaProfile());
        CertificateDetailDto certificateDetailDto = certificateService.getCertificate(certificateSecuredUuid);

        Assertions.assertEquals(1, certificateDetailDto.getMetadata().size());
        Assertions.assertEquals(connector.getName(), certificateDetailDto.getMetadata().getFirst().getConnectorName());
        Assertions.assertEquals(1, certificateDetailDto.getMetadata().getFirst().getItems().size());
    }

    @Test
    void testUpdateRaProfileFails() {
        mockServer.stubFor(WireMock
                .post(WireMock.urlPathMatching("/v2/authorityProvider/authorities/[^/]+/certificates/identify"))
                .willReturn(WireMock.jsonResponse("{\"message\": \"Object of type 'Certificate' not identified.\"}", 404)));

        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setRaProfileUuid(raProfile.getUuid().toString());

        Assertions.assertThrows(CertificateOperationException.class, () -> certificateService.updateCertificateObjects(certificate.getSecuredUuid(), uuidDto));

        mockServer.stubFor(WireMock
                .post(WireMock.urlPathMatching("/v2/authorityProvider/authorities/[^/]+/certificates/identify"))
                .willReturn(WireMock.jsonResponse("[\"Object of type 'Certificate' identified but not valid according RA profile attributes.\"]", 422)));

        Assertions.assertThrows(CertificateOperationException.class, () -> certificateService.updateCertificateObjects(certificate.getSecuredUuid(), uuidDto));
    }

    @Test
    void testUpdateRaProfile_certificateNotFound() {
        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setRaProfileUuid(raProfile.getUuid().toString());
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.updateCertificateObjects(SecuredUUID.fromString("abfbc322-29e1-11ed-a261-0242ac120002"), uuidDto));
    }

    @Test
    void testUpdateRaProfile_raProfileNotFound() {
        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setRaProfileUuid("abfbc322-29e1-11ed-a261-0242ac120002");
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.updateCertificateObjects(certificate.getSecuredUuid(), uuidDto));
    }

    @Test
    void testUpdateCertificateGroup() throws NotFoundException, CertificateOperationException, AttributeException {
        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setGroupUuids(List.of(group.getUuid().toString()));

        certificate.setArchived(true);
        certificateRepository.save(certificate);
        SecuredUUID certificateSecuredUuid = certificate.getSecuredUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.updateCertificateObjects(certificateSecuredUuid, uuidDto));
        Certificate certificateEntity = certificateRepository.findWithAssociationsByUuid(certificate.getUuid()).orElseThrow();
        Assertions.assertTrue(certificateEntity.getGroups().isEmpty());

        certificate.setArchived(false);
        certificateRepository.save(certificate);

        certificateService.updateCertificateObjects(certificateSecuredUuid, uuidDto);
        certificateEntity = certificateRepository.findWithAssociationsByUuid(certificate.getUuid()).orElseThrow();
        Assertions.assertEquals(1, certificateEntity.getGroups().size());
        Assertions.assertEquals(group.getUuid(), certificateEntity.getGroups().stream().findFirst().get().getUuid());

        associationService.removeGroup(Resource.CERTIFICATE, certificate.getUuid(), group.getUuid());
        certificateEntity = certificateRepository.findWithAssociationsByUuid(certificate.getUuid()).orElseThrow();
        Assertions.assertEquals(0, certificateEntity.getGroups().size());
    }

    @Test
    void testUpdateCertificateGroup_certificateNotFound() {
        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setGroupUuids(List.of(group.getUuid().toString()));
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.updateCertificateObjects(SecuredUUID.fromString("abfbc322-29e1-11ed-a261-0242ac120002"), uuidDto));
    }

    @Test
    void testUpdateCertificateGroup_groupNotFound() {
        CertificateUpdateObjectsDto uuidDto = new CertificateUpdateObjectsDto();
        uuidDto.setGroupUuids(List.of(UUID.randomUUID().toString()));
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.updateCertificateObjects(certificate.getSecuredUuid(), uuidDto));
    }

    @Test
    void testUpdateTrustedCaMark() throws CertificateOperationException, NotFoundException, AttributeException {
        certificate.setArchived(true);
        certificateRepository.save(certificate);
        CertificateUpdateObjectsDto request = new CertificateUpdateObjectsDto();
        request.setTrustedCa(true);
        SecuredUUID uuid = certificate.getSecuredUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.updateCertificateObjects(uuid, request));
        certificate.setArchived(false);
        certificate.setTrustedCa(false);
        certificateRepository.save(certificate);
        certificateService.updateCertificateObjects(uuid, request);
        certificate = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertTrue(certificate.getTrustedCa());
    }


    @Test
    void testUpdateOwner() throws NotFoundException, CertificateOperationException, AttributeException {
        WireMockServer mockServerUser = mockUpdateUser();

        CertificateUpdateObjectsDto request = new CertificateUpdateObjectsDto();
        request.setOwnerUuid(UUID.randomUUID().toString());

        certificate.setArchived(true);
        certificateRepository.save(certificate);
        String oldOwnerUsername = certificate.getOwner().getOwnerUsername();
        SecuredUUID certificateSecuredUuid = certificate.getSecuredUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.updateCertificateObjects(certificateSecuredUuid, request));
        NameAndUuidDto owner = associationService.getOwner(Resource.CERTIFICATE, certificate.getUuid());
        Assertions.assertEquals(oldOwnerUsername, owner.getName());

        certificate.setArchived(false);
        certificateRepository.save(certificate);
        certificateService.updateCertificateObjects(certificateSecuredUuid, request);

        // use association service to load certificate owner association since owner is not lazy loaded to mapped certificate relation due to scope of transaction in test
        owner = associationService.getOwner(Resource.CERTIFICATE, certificate.getUuid());
        Assertions.assertNotNull(owner);
        Assertions.assertEquals(request.getOwnerUuid(), owner.getUuid());
        Assertions.assertEquals("newOwner", owner.getName());

        mockServerUser.stubFor(WireMock.get(WireMock.urlPathMatching("/auth/users/[^/]+")).willReturn(
                WireMock.okJson("{ \"username\": \"newOwner2\"}")
        ));
        request.setOwnerUuid(UUID.randomUUID().toString());
        certificateService.updateCertificateObjects(certificateSecuredUuid, request);

        owner = associationService.getOwner(Resource.CERTIFICATE, certificate.getUuid());
        Assertions.assertNotNull(owner);
        Assertions.assertEquals(request.getOwnerUuid(), owner.getUuid());
        Assertions.assertEquals("newOwner2", owner.getName());

        request.setOwnerUuid("");
        certificateService.updateCertificateObjects(certificateSecuredUuid, request);
        owner = associationService.getOwner(Resource.CERTIFICATE, certificate.getUuid());
        Assertions.assertNull(owner);
        mockServerUser.stop();
    }

    private WireMockServer mockUpdateUser() {
        WireMockServer mockServerUpdateUser = new WireMockServer(AUTH_SERVICE_MOCK_PORT);
        mockServerUpdateUser.start();
        WireMock.configureFor("localhost", mockServerUpdateUser.port());
        mockServerUpdateUser.stubFor(WireMock.get(WireMock.urlPathMatching("/auth/users/[^/]+")).willReturn(
                WireMock.okJson("{ \"username\": \"newOwner\"}")
        ));
        return mockServerUpdateUser;
    }

    @Test
    void testUpdateCertificateOwner_certificateNotFound() {
        CertificateUpdateObjectsDto dto = new CertificateUpdateObjectsDto();
        dto.setOwnerUuid("testOwner");
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.updateCertificateObjects(SecuredUUID.fromString("abfbc322-29e1-11ed-a261-0242ac120002"), dto));
    }

    @Test
    void testUpdateCertificateUserArchived() {
        certificate.setArchived(true);
        certificateRepository.save(certificate);
        UUID certificateUuid = certificate.getUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.updateCertificateUser(certificateUuid, null));
        certificate.setArchived(false);
        certificateRepository.save(certificate);
        Assertions.assertDoesNotThrow(() -> certificateService.updateCertificateUser(certificateUuid, null));
    }

    @Test
    void testBulkRemove() throws NotFoundException {
        RemoveCertificateDto request = new RemoveCertificateDto();
        request.setUuids(List.of(certificate.getUuid().toString()));

        certificateService.bulkDeleteCertificate(SecurityFilter.create(), request);

        Assertions.assertThrows(NotFoundException.class, () -> certificateService.getCertificate(certificate.getSecuredUuid()));
    }

    @Test
    void testDownloadCertificate() throws NotFoundException, CertificateException, IOException {
        CertificateContent certificateContentDownload = new CertificateContent();
        certificateContentDownload.setContent("MIIOaTCCBN2gAwIBAgIUYMDCBGsuMhyBlmH99mpLcOVcHEcwDQYLKwYBBAECggsHBAQwGjEYMBYGA1UEAwwPQ29uY3plcnQgU1VCIENBMB4XDTIzMTEyMTEyMDAwMVoXDTI0MDIxOTEyMDAwMFowHTEbMBkGA1UEAwwSQ29uY3plcnQgREVNTyB1c2VyMIIDujANBgsrBgEEAYGwGgUFAgOCA6cABIIDojEpAWK5BJq6dJLtxDhapKKnYC2tyMzgFWObi0OBXt48NkzW+uA31ST1BGt0NrvqICFxehqsCVaVHkSVxQkar/Cd+feD8HZJodPAF50BQQDH5srd5rZg4ZreZ7PfJ9ruAk0ZkRgrc1l9qKu2haau0gnutOL6tyTRmr9pgWA/QbyqCLua3for0yvKhZbHv0X2mO+NrX/C55M5VM+PIhzRmizDEdgHmFBZMnQYSqIO2snbV28ryY2+jNpxgdFTdzW6z3ce+gYCC1RYeLI7JeEHAMLuBd6z0khx0rGr1vmpOYFS701MXKWY1wAmVXi9Oe3nE6ztcInKOFTwJ8LyaOy/8ipb8HXi1UM+0woC0cnuY0JjFVEOumnZMyErfOLTCk4rj0QnwKLqf2tuq9xRtDGj5+jit3nAHAKMHO6b7uuqLb5McnUe7w2oufj2YBdVF62RPM58pGiS6hQ+Tko8Q7nIvBiA33mipKn+ex4WSFl9oEtHNhUACvvCMv+Pu85Y9Oxrz3ecUvCKIZ52iIcT7KPylRaYHngpz09MGP93kd8FD+1U2HpXDL/jm6f0tgplvXgIhRwXKFPNvLsxvX9nkiluBOvghVXAJdiqKjYFOcs12y8I3niSBzgkLrkv373plw/Z/SUFdatCWoVKqP/OzjaDePl0n7n5LaGI3gzp9rLnRKTMMHf0tQM01ctQiLQiyAsdpA0oRt+pOkhb2iR9K8Y5kH1sknOyRP3QYD4Pzc78dCu9UkEnHh+NmsqIVUz91UIIy69DzR12tWEZlIqr6AgooZmOD+ey8kMDR24HSo0Bhyvsac+UrZcGp9+y1BFCYSjq8CJyKwxDf314nkSptSw15aEBbNasp4knTvMDC9Wfwmu+YKWQysm+Rhd8IJtu8nqDBR0WdTu1V6OC2qQAf3IsFbEOTROOz+iz56ImlFAWbGIVbh5ItiRqJUB+b9MpgIgXZ0MlKPB/ZaDUsw7pn72jxWgZvvfW+MMSAle2yx9hdLtJV6yTqFkayax6R+qhxBcKZilSDn1dutzXDr1/lfGt5n630KZBqttWKx4hLJa5aKXZ+DJWil0cYYovD6fqILrFY9YiVrMLS6mmsEYwaJyIp3+DNY4d4jHozkjVj0jXfv4Dstrj474C37TSaei4VeRDhgSZUtlxZ1BcAVFL//3Ad23G+x3qKLMncL7fAL2fUyBrN8p3y+c7Kg+wgzSjhN46HgQr9Te5aqjLHAvco5dQQ8WFA6OBlzCBlDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFCcXGxGh0Oyyh3yt5pcLpmFXJ9/GMDQGA1UdJQQtMCsGCCsGAQUFBwMDBggrBgEFBQcDBAYKKwYBBAGCNwoDDAYJKoZIhvcvAQEFMB0GA1UdDgQWBBT1S87JPOfM38mcchmwoolfY6tBfjAOBgNVHQ8BAf8EBAMCBeAwDQYLKwYBBAECggsHBAQDggl1AM1Cdk2upQZTPWJF6YvsybaJUhNMWcS3pu3YfeAZY/xXDhdNsKTXUC35g9I6OI0ZipnREXGwmrhGwN2K66TyV7iCyHCaaPtZtK2tj7yePAMzhnXD2Z6tNyiftJlWuaz3uGjDxwHuCCEDsT4vLfcGWH46HBin8tGAAtyiBdOQ+IixPecEptnLJ2PPrVKU+58Gdrr1rU1dYJwpSM42MLAintvVgtmIahrLFeHwFGFUPYOL61q7ZsDaU7q31/wMGlJkpI7PhCrPlIwJHAqYUH5M0Q9hK13tvSaRlGvSISbL9PR/8uMbVwkQk2ZIKdFfELjNY/mWGY42PVI5dkZv0mYwUyZYrUo13B10decgHlsm3E6nfT16i6+J301TVaocU3Q05Np3wgyecNBsT/uet7w/9gz8kDuHgoNuBaz1qeJSLUAkFE+zzXLUxq9/omOUQ7zBMgGMXwfCQhAl/STwLtcFnxmiMWdV0cF2vMQU91mMIkKRQ60SbplSrJ1sObBvXL0LVSsKPkSqQO4xyBWiDO2jHc5t8Tw8vIiU8eoLU4Lxc5054e8X+Qlzz8DP2JOPGApoizi1nlmD8DsxmM8kpLMkqOCHJ54hybKGFXq84akMuJ99ug2XTqJ6OtPX3L01l9fcYO/bKDQXjjAxiQ+rg4Fqxt3sh+qTwl2DKbA17Bd3UDyeZx6OuP1ZIf5KVRQXuFAsYaN0vmSuDln0EHoG8pPtihgLO91x8Z+QsOxlRHistTRFmsCVkHuquwvEDAU3HUQZ3CeCRHdsTEuQrfbCLbi/4Xc2am6jq4/iU/hH95DWOoPkYEn3tYj3JdF2ltY1lxEHHRw4U4U6HwcnFG5XXIPHij6YFw0VIzejDfEidebWE/M0oIM/nFS5sGV90wsJl7vudWoLf4kDNQBR1oFthIBm95qfjolWpcSg7oCh6EkeRQwMQLaAqQQJoNfrtD56U0hEMc7UZ6w5/Ly/AdJ8rQxU+2Ycd6HHRMBxNS8xsBJzzuR93IYRc8h4R+oOn+QQmW/5H/LUE8Du7eLAJ+CCazbX/pinMkpbvKRCn7v0of/0whALueExnx84o4sK+rCMcExSAQaW4sVwPo0eUwZC96xkHiGUuVlHngPndzpISMMbyJyGj9o8sXbcNRbq9Gq5Rznw7ymJnh4yJe4Ah+eTAg53CP2UjHr+hLJI+Nho04YbtgFVPBCf5I4J3VsaOlU4GQbN38Y7yfE6x6T8tOiMM4fnQkIIfaQVI8UQ8X2JaVHg0gyACM/FE/puaHqUgVk3BEg2mq+f5uRtAO5a2mvW3Ul7uAyUitLAv2mtQMZUvLUPu7ogxgde/jh7zvCrfI6jkj8x/9r5bD6XB7hvXwzsohtjxiIK8+k/a7hdt+G3Rxo0qlxOBGaIEo/Dv9Duotlgr9c9H5rbcTVNMEsqYXPCnaFPqSojAWTu+w594Jixed7vAdg2Yiy4jL9YXGOStbQGk8vhZCSrkbx0xUqxzBmuzQEA/EcJEwwXVl1gKS8ZD1fUi7Qp+q0SIHOIFF70yOBeK1HQVpfP5IxydHRzfeGPMAvXRgoUJBhFJRZy72bWE+URceqHVfH6yLvlmqmpc663XUoEj+PbOEUDkayBk7Rbgmh/AWk5a4cJC2IJbkvgt4XMWspFkPImNMFaHuUVkLquM5tCShYTaEGmGsFD6ABo6+3M4Bj1bRmM6R58lvEDjCEtxUhR3X0wItzlhTwBJr+w6Ecj8UROXEpvTKWyzTOCJC8SlNW1UNCDUUoPKKdZIK8keedh8w3x4RXKu495+iTHq7lOmLjrME1+BzFlrRzeNxj9VxLHgWj9DZkHiGhDIDI3xj+rpDfvyWykLeD2WoXtUE9H0tYwvRQQdKFMiGaDPrXwX9xl///YUP+Bm2/rvj5clHTh400B/1Ihcuhafe9RWeMBewQ+nU5si21DBZfYbliqzPkQJ1tGGzpwjH5Bg9JhR8z/RFwFsFVWzwNY7bJHmrXqxNCPs22DZq1KWoR5346wC//0hhsvycOCc94sOUlGKIo9w7AYvbJggNBiKZDlf/FA4FK1KenVxq1dHSMxRnStWLmg3njJGwrLtdyBp4vvUsRW+JHVoV0wyNzf9mx8KWe2s9dC2g1n8TmS/nE2yDGO3RnQDccJ6EWS+SwFrTyvVeusw1AgRviRjDo5JqMAKv/Pz57mhf11HEA+MGtRBFD9lYnpVdGgH1of1TEKMdMEbY9gHFC8UoOvm3h64ticheQJlTpcZumxBTSdn6d72KxV7dV0LhQRfaZEgTTvEOcb4bqjUjxM3355Xtgb4IxJFdpQ8wJZfRJWKtXrZ2fcfhPrQ+bLeFX5X93OQpuFRNyt9IV3ng1EE0ZMKkSifB7FCYnLiymoLRXUd75KBglrFoJs/AiTOZw+qyRr46pXz40Qplg8oek5yN4V7/7V8aXGkAQvSLc0v5tL00tWHAhJn5zR8lgaUTYI8vsGWtXPTdfN2Su9lQxrczAfe6UmQQ15Ad1iBtsFxrlFQ1htXFQDNX5AtChgMevOTmPTWRVYn29eBg6nYS5B8p7lp/I5PJqXr4UlPp9ioxomjJNXJhw1thWf9yxWAj/9jTn4HtJyNRasMcWZkkEJfbH+ud13ekrdEMNdLfzVOt748VoDGo8KSE5zT7IkDJfJn+B9CHLkiqLbfYUiYM2RkPKGFLrSSBCxq+04rZF3fHZcsFFg5GZhI6dcc8kSmMFFFQyXyXGSoPmWmLF00vg1xUArv2RsTQm/EBx2VO62u2KQk857jupMe2ISsZgKpf5RU4A4ph7YxN5WALD4DNpdBe3tGQkWUgTstvRlmAWKhAoeKqzxyFncKy4uJuBip6VKF4TsfWi4E8UpwhFa09C9g8XGW7+U2N91nEXqqbclTnQUJbE7Cf2NwA9ybnXZ8dIE69N7VfnomsuW4YbzjWOcSY8lqJ78duqmUoCYWKnPzj97ncRshbM/nOfQyV6wpySBPJNsvgh7RwTh9ngV0J1Suo7rt+V3UDqZhre1+tJDNkj10DqYTdNIYdDpxXy22fqK7uBSJFMsBjoBzTmR91ahWDv4nu1f3Z+kOxvcLEhJbyGx+FFWuvtG7+Htcc5sNNaVFqnuWYFhyizZx3E6AiE1QEhdZ22FlcvOECE7PlJcbW50d5WxtczO0NMAPWaMsLW4wc3R5foGITqIi6Wzvb7J1dvv9PcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMHSk4");
        certificateContentDownload = certificateContentRepository.save(certificateContentDownload);
        certificate.setCertificateContent(certificateContentDownload);
        certificateRepository.save(certificate);
        testDownloadInternal(CertificateFormat.RAW, CertificateFormatEncoding.PEM);
        testDownloadInternal(CertificateFormat.RAW, CertificateFormatEncoding.DER);
        testDownloadInternal(CertificateFormat.PKCS7, CertificateFormatEncoding.PEM);
        testDownloadInternal(CertificateFormat.PKCS7, CertificateFormatEncoding.DER);
    }

    @Test
    void testUploadCertificateKey() throws com.czertainly.api.exception.CertificateException, CertificateEncodingException, NotFoundException {
        Certificate certificateWithKey = certificateService.createCertificate(Base64.getEncoder().encodeToString(x509Cert.getEncoded()), CertificateType.X509);
        UUID keyUuid = certificateWithKey.getKeyUuid();
        Assertions.assertNotNull(keyUuid);
        // Check if key already in DB is assigned to the certificate
        certificateService.deleteCertificate(certificateWithKey.getSecuredUuid());
        certificateWithKey = certificateService.createCertificate(Base64.getEncoder().encodeToString(x509Cert.getEncoded()), CertificateType.X509);
        Assertions.assertEquals(keyUuid, certificateWithKey.getKeyUuid());
    }

    @Test
    void testDeleteCertificateWithUser() throws CertificateEncodingException, com.czertainly.api.exception.CertificateException {
        Certificate certificateNew = certificateService.createCertificate(Base64.getEncoder().encodeToString(x509Cert.getEncoded()), CertificateType.X509);
        certificateNew.setUserUuid(UUID.randomUUID());
        certificateRepository.save(certificateNew);
        SecuredUUID uuid = certificateNew.getSecuredUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.deleteCertificate(uuid));
    }

    @Test
    void bulkUpdate() throws CertificateException, com.czertainly.api.exception.CertificateException, NotFoundException, IOException {
        Certificate certificateNew = certificateService.createCertificate(Base64.getEncoder().encodeToString(x509Cert.getEncoded()), CertificateType.X509);

        MultipleCertificateObjectUpdateDto request = new MultipleCertificateObjectUpdateDto();
        request.setCertificateUuids(List.of(certificateNew.getUuid().toString()));
        request.setGroupUuids(List.of(group.getUuid().toString()));
        certificateService.bulkUpdateCertificatesObjects(SecurityFilter.create(), request);

        CertificateDetailDto detailDto = certificateService.getCertificate(certificateNew.getSecuredUuid());
        Assertions.assertEquals(1, detailDto.getGroups().size());
        Assertions.assertEquals(group.getUuid().toString(), detailDto.getGroups().getFirst().getUuid());
    }

    @Test
    void testGetSearchableFieldInformation() {
        mockServer = new WireMockServer(AUTH_SERVICE_MOCK_PORT);
        mockServer.start();
        WireMock.configureFor("localhost", mockServer.port());
        mockServer.stubFor(WireMock.get(WireMock.urlPathMatching("/auth/users")).willReturn(
                WireMock.okJson("{ \"data\": [] }")
        ));
        Assertions.assertDoesNotThrow(() -> certificateService.getSearchableFieldInformationByGroup());
        mockServer.stop();
    }

    @Test
    void testClearKeyAssociations() {
        CryptographicKey key = new CryptographicKey();
        cryptographicKeyRepository.save(key);
        certificate.setKey(key);
        certificate.setKeyUuid(key.getUuid());
        Certificate altCertificate = new Certificate();
        CertificateContent altContent = new CertificateContent();
        altContent.setContent("content");
        certificateContentRepository.save(altContent);
        altCertificate.setCertificateContent(altContent);
        altCertificate.setAltKey(key);
        altCertificate.setAltKeyUuid(key.getUuid());
        certificateRepository.save(certificate);
        certificateRepository.save(altCertificate);
        certificateService.clearKeyAssociations(key.getUuid());
        certificate = certificateRepository.findByUuid(certificate.getUuid()).get();
        altCertificate = certificateRepository.findByUuid(altCertificate.getUuid()).get();
        Assertions.assertNull(certificate.getKey());
        Assertions.assertNull(certificate.getKeyUuid());
        Assertions.assertNull(altCertificate.getAltKey());
        Assertions.assertNull(altCertificate.getAltKeyUuid());
    }

    @Test
    void testArchiveCertificate() throws NotFoundException {
        certificateService.unarchiveCertificate(certificate.getUuid());
        certificate = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertFalse(certificate.isArchived());

        certificateService.archiveCertificate(certificate.getUuid());
        certificate = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertTrue(certificate.isArchived());

        certificateService.bulkUnarchiveCertificates(List.of(certificate.getUuid()));
        certificate = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertFalse(certificate.isArchived());

        certificateService.bulkArchiveCertificates(List.of(certificate.getUuid()));
        certificate = certificateRepository.findByUuid(certificate.getUuid()).get();
        Assertions.assertTrue(certificate.isArchived());
    }

    @Test
    void testListCmpCertificates() {
        certificate.setArchived(true);
        certificateRepository.save(certificate);
        Assertions.assertTrue(certificateService.listCmpSigningCertificates(new SecurityFilter()).isEmpty());
    }

    private void testDownloadInternal(CertificateFormat format, CertificateFormatEncoding encoding) throws NotFoundException, CertificateException, IOException {
        CertificateDownloadResponseDto certificateDownloadResponseDto = certificateService.downloadCertificate(certificate.getUuid(), format, encoding);
        Assertions.assertDoesNotThrow(() -> (certificateService.createCertificate(certificateDownloadResponseDto.getContent(), CertificateType.X509)));
    }

    @Test
    void testCheckCompliance() throws NotFoundException {
        certificate.setArchived(true);
        certificateRepository.save(certificate);
        ComplianceStatus oldComplianceStatus = certificate.getComplianceStatus();
        CertificateComplianceCheckDto request = new CertificateComplianceCheckDto();
        request.setCertificateUuids(List.of(certificate.getUuid().toString()));
        certificateService.checkCompliance(request);
        Assertions.assertEquals(oldComplianceStatus, certificateRepository.findByUuid(certificate.getUuid()).get().getComplianceStatus());
    }

    @Test
    void testUpdateDns() {
        String oid = "1.2.3";
        String oldCode = "OU";
        String newCode = "OO";
        certificate.setSubjectDn("%s=org, %sA=cn".formatted(oldCode, oldCode));
        certificate.setSubjectDnNormalized("%s=org".formatted(oid));
        certificate.setIssuerDn("CN=cn, %s=org".formatted(oldCode));
        certificate.setIssuerDnNormalized("1.2.3.4=a, %s=f".formatted(oid));
        certificateRepository.save(certificate);
        certificateService.updateCertificateDNs(oid, newCode, oldCode);
        certificate = certificateRepository.findByUuid(certificate.getUuid()).orElseThrow();
        Assertions.assertEquals("%s=org, %sA=cn".formatted(newCode, oldCode), certificate.getSubjectDn());
        Assertions.assertEquals("CN=cn, %s=org".formatted(newCode), certificate.getIssuerDn());

        certificate.setIssuerDn("%s=org, CN=cn".formatted(oldCode));
        certificate.setSubjectDn("CN=cn, %s=org".formatted(oldCode));
        certificateRepository.save(certificate);
        certificateService.updateCertificateDNs(oid, newCode, oldCode);
        certificate = certificateRepository.findByUuid(certificate.getUuid()).orElseThrow();
        Assertions.assertEquals("%s=org, CN=cn".formatted(newCode), certificate.getIssuerDn());
        Assertions.assertEquals("CN=cn, %s=org".formatted(newCode), certificate.getSubjectDn());

        certificate.setIssuerDnNormalized("1.2.3.4=a, 1a2x3=f");
        certificateRepository.save(certificate);
        certificateService.updateCertificateDNs(oid, "new", newCode);
        certificate = certificateRepository.findByUuid(certificate.getUuid()).orElseThrow();
        Assertions.assertEquals("%s=org, CN=cn".formatted(newCode), certificate.getIssuerDn());


    }

    @Test
    void testSetProtocolCertificateAssociations() throws AlreadyExistException, AttributeException, NotFoundException, NoSuchAlgorithmException, ConnectorException, CertificateRequestException {
        WireMockServer mockServerUpdateUser = mockUpdateUser();
        mockServer.stubFor(WireMock
                .post(WireMock.urlPathMatching("/v2/authorityProvider/authorities/[^/]+/certificates/issue/attributes/validate"))
                .willReturn(WireMock.okJson("true")));
        mockServer.stubFor(WireMock
                .get(WireMock.urlPathMatching("/v2/authorityProvider/authorities/[^/]+/certificates/issue/attributes"))
                .willReturn(WireMock.okJson("[]")));

        AcmeProfile acmeProfile = getAcmeProfile();
        CertificateProtocolInfo protocolInfo = new CertificateProtocolInfo();
        protocolInfo.setProtocol(CertificateProtocol.ACME);
        protocolInfo.setProtocolProfileUuid(acmeProfile.getUuid());
        CertificateDetailDto certificateDetailDto = certificateService.submitCertificateRequest(
                SAMPLE_PKCS10, CertificateRequestFormat.PKCS10, List.of(), List.of(), List.of(), List.of(),
                null, null, raProfile.getUuid(), null, protocolInfo);
        Certificate certificateToBeIssued = certificateRepository.findWithAssociationsByUuid(UUID.fromString(certificateDetailDto.getUuid())).orElseThrow();
        Assertions.assertEquals(Set.of(group), certificateToBeIssued.getGroups());
        Assertions.assertNotNull(associationService.getOwner(Resource.CERTIFICATE, certificateToBeIssued.getUuid()));
        Assertions.assertNotNull(attributeEngine.getObjectCustomAttributesContent(Resource.CERTIFICATE, certificateToBeIssued.getUuid()));
        mockServer.stop();
        mockServerUpdateUser.stop();
    }

    @Test
    void testCertificateRelations() throws NotFoundException {
        certificate.setIssuerDnNormalized("issuerDn");
        certificate.setSubjectDnNormalized("subjectDn");
        certificate.setIssuerSerialNumber("serialNumber");
        CryptographicKey key = new CryptographicKey();
        cryptographicKeyRepository.save(key);
        certificate.setPublicKeyFingerprint("finger");
        Certificate sourceCertificate1 = new Certificate();
        sourceCertificate1.setIssuerDnNormalized(certificate.getIssuerDnNormalized());
        sourceCertificate1.setSubjectDnNormalized(certificate.getSubjectDnNormalized());
        sourceCertificate1.setIssuerSerialNumber(certificate.getIssuerSerialNumber());
        sourceCertificate1.setPublicKeyFingerprint(certificate.getPublicKeyFingerprint());
        Certificate sourceCertificate2 = new Certificate();
        sourceCertificate2.setIssuerDnNormalized(certificate.getIssuerDnNormalized());
        sourceCertificate2.setSubjectDnNormalized(certificate.getSubjectDnNormalized());
        sourceCertificate2.setIssuerSerialNumber(certificate.getIssuerSerialNumber());
        Certificate sourceCertificate3 = new Certificate();
        certificateRepository.saveAll(List.of(sourceCertificate1, sourceCertificate2, sourceCertificate3, certificate));
        UUID certificateUuid = certificate.getUuid();
        UUID certificateUuid1 = sourceCertificate1.getUuid();
        Assertions.assertThrows(ValidationException.class, () -> certificateService.associateCertificates(certificateUuid, certificateUuid1));
        sourceCertificate1.setState(CertificateState.ISSUED);
        sourceCertificate2.setState(CertificateState.ISSUED);
        sourceCertificate3.setState(CertificateState.REVOKED);
        certificateRepository.saveAll(List.of(sourceCertificate1, sourceCertificate2, sourceCertificate3, certificate));

        Assertions.assertThrows(ValidationException.class, () -> certificateService.associateCertificates(certificateUuid, certificateUuid));

        certificateService.associateCertificates(certificateUuid, certificateUuid1);
        Assertions.assertThrows(ValidationException.class, () -> certificateService.associateCertificates(certificateUuid, certificateUuid1));

        certificate.setSubjectType(CertificateSubjectType.END_ENTITY);
        sourceCertificate1.setSubjectType(CertificateSubjectType.ROOT_CA);
        certificateRepository.saveAll(List.of(sourceCertificate1, certificate));
        Assertions.assertThrows(ValidationException.class, () -> certificateService.associateCertificates(certificateUuid, certificateUuid1));

        sourceCertificate1.setSubjectType(CertificateSubjectType.SELF_SIGNED_END_ENTITY);
        certificateRepository.save(sourceCertificate1);

        certificateService.associateCertificates(certificateUuid, sourceCertificate2.getUuid());
        UUID certificate3Uuid = sourceCertificate3.getUuid();
        certificate.setState(CertificateState.REVOKED);
        certificate.setIssuerSerialNumber(null);
        sourceCertificate3.setIssuerSerialNumber(null);
        certificateRepository.save(certificate);
        certificateRepository.save(sourceCertificate3);
        certificateService.associateCertificates(certificateUuid, certificate3Uuid);
        Assertions.assertThrows(ValidationException.class, () -> certificateService.associateCertificates(certificate3Uuid, certificateUuid));


        CertificateRelationsDto relations = certificateService.getCertificateRelations(certificateUuid);
        Assertions.assertEquals(certificateUuid, relations.getCertificateUuid());
        Assertions.assertEquals(3, relations.getPredecessorCertificates().size());
        CertificateSimpleDto certificateSimpleDto1 = relations.getPredecessorCertificates().stream().filter(dto -> dto.getUuid().equals(certificateUuid1)).findFirst().orElseThrow();
        Assertions.assertEquals(CertificateRelationType.RENEWAL, certificateSimpleDto1.getRelationType());
        CertificateSimpleDto certificateSimpleDto2 = relations.getPredecessorCertificates().stream().filter(dto -> dto.getUuid().equals(sourceCertificate2.getUuid())).findFirst().orElseThrow();
        Assertions.assertEquals(CertificateRelationType.REKEY, certificateSimpleDto2.getRelationType());
        CertificateSimpleDto certificateSimpleDto3 = relations.getPredecessorCertificates().stream().filter(dto -> dto.getUuid().equals(certificate3Uuid)).findFirst().orElseThrow();
        Assertions.assertEquals(CertificateRelationType.REPLACEMENT, certificateSimpleDto3.getRelationType());

        relations = certificateService.getCertificateRelations(certificateUuid1);
        Assertions.assertEquals(1, relations.getSuccessorCertificates().size());
        CertificateSimpleDto certificateSimpleDto = relations.getSuccessorCertificates().stream().filter(dto -> dto.getUuid().equals(certificateUuid)).findFirst().orElseThrow();
        Assertions.assertEquals(CertificateRelationType.RENEWAL, certificateSimpleDto.getRelationType());

        certificateService.removeCertificateAssociation(certificateUuid, sourceCertificate2.getUuid());
        relations = certificateService.getCertificateRelations(certificateUuid);
        Assertions.assertEquals(2, relations.getPredecessorCertificates().size());
        Assertions.assertTrue(relations.getPredecessorCertificates().stream().filter(dto -> dto.getUuid().equals(sourceCertificate2.getUuid())).findFirst().isEmpty());
        relations = certificateService.getCertificateRelations(sourceCertificate2.getUuid());
        Assertions.assertTrue(relations.getSuccessorCertificates().isEmpty());
        Assertions.assertThrows(NotFoundException.class, () -> certificateService.removeCertificateAssociation(certificateUuid, sourceCertificate2.getUuid()));

        sourceCertificate2.setNotBefore(new Date());
        certificate.setNotBefore(Date.from(Instant.now().minus(1, ChronoUnit.DAYS)));
        certificateRepository.save(sourceCertificate2);
        certificateRepository.save(certificate);
        certificateService.associateCertificates(certificateUuid, sourceCertificate2.getUuid());
        relations = certificateService.getCertificateRelations(certificateUuid);
        Assertions.assertEquals(2, relations.getPredecessorCertificates().size());
        Assertions.assertEquals(1, relations.getSuccessorCertificates().size());
        Assertions.assertTrue(relations.getSuccessorCertificates().stream().anyMatch(dto -> dto.getUuid().equals(sourceCertificate2.getUuid())));

        certificate.setState(CertificateState.FAILED);
        certificateRepository.save(certificate);
        certificateService.removeCertificateAssociation(certificateUuid, sourceCertificate1.getUuid());
        Assertions.assertThrows(ValidationException.class, () -> certificateService.associateCertificates(certificateUuid, certificateUuid1));
        certificate.setState(CertificateState.PENDING_APPROVAL);
        certificateRepository.save(certificate);
        certificateService.associateCertificates(certificateUuid, certificateUuid1);
        relations = certificateService.getCertificateRelations(certificateUuid);
        certificateSimpleDto = relations.getPredecessorCertificates().stream().filter(dto -> dto.getUuid().equals(certificateUuid1)).findFirst().orElseThrow();
        Assertions.assertEquals(CertificateRelationType.PENDING, certificateSimpleDto.getRelationType());

    }

    @Test
    void testPrepareIssuedCertificate() throws CertificateException, NoSuchAlgorithmException, NotFoundException, AlreadyExistException, AttributeException {
        Certificate commonIssuer = new Certificate();
        CertificateUtil.prepareIssuedCertificate(commonIssuer, CertificateUtil.getX509Certificate(CA_BASE64_CONTENT));
        CertificateContent issuerContent = new CertificateContent();
        issuerContent.setContent(CA_BASE64_CONTENT);
        certificateContentRepository.save(issuerContent);
        commonIssuer.setCertificateContent(issuerContent);
        certificateRepository.save(commonIssuer);
        Certificate notIssued = new Certificate();
        notIssued.setRaProfile(raProfile);
        certificateRepository.save(notIssued);
        certificate.setIssuerSerialNumber(commonIssuer.getSerialNumber());
        certificate.setSubjectDnNormalized("2.5.4.3=hybrid-with-csr2");
        certificate.setIssuerDnNormalized(commonIssuer.getSubjectDnNormalized());
        certificate.setSubjectType(CertificateSubjectType.INTERMEDIATE_CA);
        CertificateRelation relation = new CertificateRelation();
        relation.setRelationType(CertificateRelationType.PENDING);
        relation.setSuccessorCertificate(notIssued);
        relation.setPredecessorCertificate(certificate);
        CertificateRelationId relationId = new CertificateRelationId(notIssued.getUuid(), certificate.getUuid());
        relation.setId(relationId);
        certificateRelationRepository.save(relation);
        certificateRepository.save(notIssued);
        certificateRepository.save(certificate);

        certificateService.issueRequestedCertificate(notIssued.getUuid(), EE_BASE64_CONTENT, null);

        CertificateRelationsDto relationsDto = certificateService.getCertificateRelations(notIssued.getUuid());
        Assertions.assertEquals(CertificateRelationType.REKEY, relationsDto.getPredecessorCertificates().getFirst().getRelationType());

        // Throw exception in update certificate chain
        notIssued.setCertificateContent(null);
        certificateRepository.save(notIssued);
        certificate.setIssuerSerialNumber(null);
        certificateRepository.save(certificate);
        relation.setRelationType(CertificateRelationType.PENDING);
        certificateRelationRepository.save(relation);
        certificateService.issueRequestedCertificate(notIssued.getUuid(), EE_BASE64_CONTENT, null);

        relationsDto = certificateService.getCertificateRelations(notIssued.getUuid());
        Assertions.assertEquals(CertificateRelationType.REPLACEMENT, relationsDto.getPredecessorCertificates().getFirst().getRelationType());
    }

    @NotNull
    private AcmeProfile getAcmeProfile() throws AlreadyExistException, AttributeException {
        AcmeProfile acmeProfile = new AcmeProfile();
        acmeProfile.setWebsite("sample website");
        acmeProfile.setTermsOfServiceUrl("sample terms");
        acmeProfile.setValidity(30);
        acmeProfile.setRetryInterval(30);
        acmeProfile.setDescription("sample description");
        acmeProfile.setName("sameName");
        acmeProfile.setDnsResolverPort("53");
        acmeProfile.setDnsResolverIp("localhost");
        acmeProfile.setTermsOfServiceChangeUrl("change url");
        acmeProfile.setEnabled(false);
        ProtocolCertificateAssociations protocolCertificateAssociations = getProtocolCertificateAssociation();
        acmeProfile.setCertificateAssociations(protocolCertificateAssociations);
        acmeProfile.setCertificateAssociationsUuid(protocolCertificateAssociations.getUuid());
        acmeProfileRepository.save(acmeProfile);
        protocolCertificateAssociationsRepository.save(protocolCertificateAssociations);
        return acmeProfile;
    }

    @NotNull
    private ProtocolCertificateAssociations getProtocolCertificateAssociation() throws AlreadyExistException, AttributeException {
        ProtocolCertificateAssociations protocolCertificateAssociations = new ProtocolCertificateAssociations();
        protocolCertificateAssociations.setOwnerUuid(UUID.randomUUID());
        protocolCertificateAssociations.setGroupUuids(List.of(group.getUuid()));
        CustomAttributeCreateRequestDto customAttributeRequest = new CustomAttributeCreateRequestDto();
        customAttributeRequest.setName("name");
        customAttributeRequest.setLabel("name");
        customAttributeRequest.setResources(List.of(Resource.CERTIFICATE));
        customAttributeRequest.setContentType(AttributeContentType.STRING);
        String attributeUuid = attributeService.createCustomAttribute(customAttributeRequest).getUuid();
        RequestAttributeV3 requestAttribute = new RequestAttributeV3();
        requestAttribute.setUuid(UUID.fromString(attributeUuid));
        requestAttribute.setName(customAttributeRequest.getName());
        requestAttribute.setContentType(customAttributeRequest.getContentType());
        requestAttribute.setContent(List.of(new StringAttributeContentV3("ref", "data")));
        protocolCertificateAssociations.setCustomAttributes(List.of(requestAttribute));
        protocolCertificateAssociationsRepository.save(protocolCertificateAssociations);
        return protocolCertificateAssociations;
    }
}
