#!/bin/bash

echo "Pre-build CZERTAINLY CORE docker image"

echo "Cleaning containers if exists"
docker rm czertainlycont
docker rmi prebuild

echo "Refreshing directory for data from container"
rm -r data
mkdir data

echo "PreBuild build"
docker build -f Dockerfile-pre -t prebuild .

echo "MVN Build"
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "MacOS detected, using TESTCONTAINERS_HOST_OVERRIDE"
  docker run -e TESTCONTAINERS_HOST_OVERRIDE=docker.for.mac.host.internal -v /var/run/docker.sock:/var/run/docker.sock --name czertainlycont -i prebuild mvn -f /home/app/pom.xml -U clean package
else
  docker run -v /var/run/docker.sock:/var/run/docker.sock --name czertainlycont -i prebuild mvn -f /home/app/pom.xml -U clean package
fi

echo "Starting czertainlycont"
docker start czertainlycont

echo "Copy jar back to Tmp"
docker cp czertainlycont:/home/app/target data/target
docker cp czertainlycont:/home/app/docker data/docker
