#!/bin/bash

echo "Build of CZERTAINLY CORE"

echo "Cleaning containers"
docker rm czertainlycont
docker rmi prebuild

echo "Refreshing directory for data from container"
rm -r data
mkdir data

echo "PreBuild build"
docker build --build-arg SERVER_USERNAME=$SERVER_USERNAME --build-arg SERVER_PASSWORD=$SERVER_PASSWORD -f $DOCKERFILE_PATH-pre -t prebuild .

echo "MVN Build"
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "MacOS detected, using TESTCONTAINERS_HOST_OVERRIDE"
  docker run -e TESTCONTAINERS_HOST_OVERRIDE=docker.for.mac.host.internal -v /var/run/docker.sock:/var/run/docker.sock --name czertainlycont -i prebuild mvn -f /home/app/pom.xml clean package
else
  docker run -v /var/run/docker.sock:/var/run/docker.sock --name czertainlycont -i prebuild mvn -f /home/app/pom.xml clean package
fi

echo "Starting czertainlycont"
docker start -d --restart=always czertainlycont

echo "Copy jar back to Tmp"
docker cp czertainlycont:/home/app/target data/target
docker cp czertainlycont:/home/app/docker data/docker

echo "Removing previous image"
docker rmi $IMAGE_NAME

echo "Build main image"
docker build --platform linux/amd64,linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

echo "Cleaning workspace"
rm -r data
