#!/bin/bash

echo "Build of CZERTAINLY CORE"

echo "Cleaning containers"
docker rm czertainlycont
docker rmi prebuild

echo "Removing the tmp directory"
rm -r /tmp/docker
rm -r /tmp/target

echo "PreBuild build"
docker build --build-arg SERVER_USERNAME=blausername --build-arg SERVER_PASSWORD=pws123 -f $DOCKERFILE_PATH-pre -t prebuild .

echo "MVN Build"
docker run -v /var/run/docker.sock:/var/run/docker.sock --name czertainlycont -i prebuild mvn -f /home/app/pom.xml clean package

echo "Print dockers"
docker images
docker ps -a

echo "Starting czertainlycont"
docker start -d --restart=always czertainlycont

echo "Copy jar back to Tmp"
docker cp czertainlycont:/home/app/target /tmp
docker cp czertainlycont:/home/app/docker /tmp

echo "List files"
ls -la /tmp

echo "Build main image"
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
