CREATE SCHEMA IF NOT EXISTS core;

-- SB4.1 pilot (RC#5): Boot 4 commits a session on MockMvc requests, so the test profile needs
-- these tables. Flyway is disabled in tests and Hibernate ddl-auto cannot create them because
-- they are not JPA entities. IF NOT EXISTS is mandatory: the Testcontainer is reused across
-- Spring contexts and spring.sql.init.mode=always re-runs this script for each one.
CREATE TABLE IF NOT EXISTS core.SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON core.SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON core.SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON core.SPRING_SESSION (PRINCIPAL_NAME);
CREATE TABLE IF NOT EXISTS core.SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES JSONB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES core.SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
