CREATE TABLE setting (
	uuid UUID NOT NULL,
	i_author VARCHAR NOT NULL,
	i_cre TIMESTAMP NOT NULL,
	i_upd TIMESTAMP NOT NULL,
	name VARCHAR NULL DEFAULT NULL,
	"section" VARCHAR NOT NULL,
	data TEXT NOT NULL
);