ALTER TABLE SPRING_SESSION_ATTRIBUTES DROP CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK;

ALTER TABLE SPRING_SESSION_ATTRIBUTES
ADD CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK
FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE;