name: Publish Docker image

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}-harbor
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    uses: OmniTrustILM/.github/.github/workflows/containers-build-and-push.yml@main
    secrets: inherit
    with:
      image: ilm/core
      cache-scope: core
      pre-build: maven
      build-args: |
        VERSION=${{ github.ref_name }}
