name: Sonar
on:
  workflow_run:
    workflows: ["Build PR"]
    types: [completed]

jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      # Download compiled classes
      - name: Download Compiled Classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: target/classes
      # Download Jacoco XML coverage files
      - name: Download Coverage Reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: target/site/jacoco
      # Now download the PR number artifact
      - name: Download PR number
        uses: actions/download-artifact@v4
        with:
          name: pr-number
          path: .
      - name: Debug PR number
        run: |
          PR_NUMBER=$(cat pr-number.txt)
          echo "We got PR number: ${PR_NUMBER}"
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          PR_NUMBER=$(cat pr-number.txt)
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }} \
            -Dsonar.pullrequest.key=${PR_NUMBER}
