name: Test Docker image

on:
  pull_request:
    branches: [ main*, feat/*, hotfix/* ]
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}-docker-test
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  test:
    uses: OmniTrustILM/.github/.github/workflows/containers-test.yml@main
    secrets: inherit
    with:
      image: ilm/core
      cache-scope: core
      pre-build: maven
      build-args: |
        VERSION=${{ github.ref_name }}
